import { vfBreakpoints } from '../../../theme/src/breakpoints';
import { vfMotionTokens } from '../../../theme/src/motion';
import type { VfPrimitiveColorTokenName, VfSemanticColorTokenName } from '../../../theme/src/color-token-contract';
import type { VfThemePreset, VfThemeTokens } from '@/types/theme';
import {
  legacyDarkColorTokens,
  legacyLightColorTokens,
  primitiveColorTokens,
  semanticDarkColorTokens,
  semanticLightColorTokens,
} from './color-token-schema';

type AdditiveColorTokenName = VfPrimitiveColorTokenName | Exclude<VfSemanticColorTokenName, 'colorFocusRing'>;
type LegacyThemeTokens = Omit<Required<VfThemeTokens>, AdditiveColorTokenName>;

type LegacyDefaultThemePreset = Omit<VfThemePreset, 'tokens' | 'dark'> & {
  tokens: LegacyThemeTokens;
  dark?: Partial<LegacyThemeTokens>;
};

type CompleteDefaultThemePreset = Omit<VfThemePreset, 'tokens' | 'dark'> & {
  tokens: Required<VfThemeTokens>;
  dark?: Partial<Required<VfThemeTokens>>;
};

export const breakpointTokens = {
  breakpointXs: `${vfBreakpoints.xs}px`,
  breakpointSm: `${vfBreakpoints.sm}px`,
  breakpointMd: `${vfBreakpoints.md}px`,
  breakpointLg: `${vfBreakpoints.lg}px`,
  breakpointXl: `${vfBreakpoints.xl}px`,
  breakpoint2xl: `${vfBreakpoints['2xl']}px`,
};

export const legacyDefaultThemePresetSource = {
  name: 'vueforge-default',
  tokens: {
    fontFamilyBase: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyHeading: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyMono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    fontWeightRegular: '400',
    fontWeightMedium: '500',
    fontWeightSemibold: '600',
    fontWeightBold: '700',
    fontSizeXs: '0.75rem',
    fontSizeSm: '0.8125rem',
    fontSizeMd: '0.875rem',
    fontSizeLg: '0.9375rem',
    fontSizeXl: '1rem',
    fontSize2xl: '1.125rem',
    fontSize3xl: '1.25rem',
    lineHeightTight: '1.2',
    lineHeightNormal: '1.5',
    lineHeightRelaxed: '1.65',
    borderWidth: '1px',
    borderWidthThick: '2px',
    radiusRound: '999px',
    visuallyHiddenSize: '1px',
    visuallyHiddenMargin: '-1px',
    iconSizeSm: '0.875rem',
    iconSizeMd: '1rem',
    iconSizeLg: '1.125rem',
    iconSizeXl: '1.5rem',
    selectableColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    selectableHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    selectableHoverBackground: 'var(--vf-color-background-surface-hover, transparent)',
    selectableActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-primary))',
    selectableActiveBackground:
      'var(--vf-color-background-surface-selected, color-mix(in srgb, var(--vf-color-primary) 20%, var(--vf-color-surface)))',
    navMenuItemHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    navMenuItemHoverBackground: 'var(--vf-color-background-surface-hover, transparent)',
    navMenuItemActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    navMenuItemActiveBackground: 'var(--vf-color-background-surface-selected, transparent)',
    navMenuPillsItemPadding: 'var(--vf-field-padding-md)',
    navMenuPillsListGap: 'var(--vf-nav-menu-list-gap)',
    navMenuPillsNestedGap: 'var(--vf-nav-menu-nested-gap)',
    navMenuPillsCollapseOffsetTop: 'var(--vf-nav-menu-collapse-offset-top)',
    navMenuPillsItemMinHeight: 'var(--vf-control-height-md)',
    navMenuPillsItemHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    navMenuPillsItemHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    navMenuPillsItemActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    navMenuPillsItemActiveBackground: 'var(--vf-color-background-surface-selected, var(--vf-color-primary-soft))',
    navMenuPillsItemAncestorActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    navMenuSidebarItemHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    navMenuSidebarTopHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    navMenuSidebarAncestorActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    navMenuSidebarTopAncestorActiveBackground:
      'var(--vf-color-background-surface-selected, var(--vf-color-primary-soft))',
    navMenuSidebarNestedActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    navMenuSidebarRailColor: 'var(--vf-color-border-divider, var(--vf-color-border))',
    navMenuSidebarRailActiveColor: 'var(--vf-color-interactive-primary-border, var(--vf-color-primary))',
    navMenuSidebarCollapseLevel0Margin:
      'calc(var(--vf-nav-menu-collapse-inset-level-0-margin) + var(--vf-surface-gap-compact) * 2)',
    navMenuSidebarIconAlignedLevel0Margin:
      'calc(var(--vf-border-width) + var(--vf-field-padding-inline-md) + var(--vf-nav-menu-leading-icon-column-size) * 0.5)',
    navMenuSidebarLevelStep: 'calc(var(--vf-nav-menu-leading-icon-column-size) + var(--vf-nav-menu-item-gap) * 0.5)',
    navMenuSidebarNestedItemOffset: 'var(--vf-surface-gap-compact)',
    navMenuSidebarConnectorOffsetTop: 'calc(var(--vf-border-width) + var(--vf-field-padding-block-md) + 0.75rem)',
    navMenuGroupLabelColor: 'var(--vf-color-text-secondary, var(--vf-color-text))',
    navMenuItemColor: 'var(--vf-selectable-color)',
    navMenuTopItemFontWeight: 'var(--vf-text-label-font-weight)',
    navMenuItemRadius: 'var(--vf-radius-control)',
    navMenuItemFocusColor: 'var(--vf-color-selected-foreground, var(--vf-color-primary))',
    navMenuItemFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    navMenuItemAncestorActiveColor: 'var(--vf-selectable-color)',
    navMenuBranchColor: 'var(--vf-selectable-color)',
    navMenuBranchAncestorActiveColor: 'var(--vf-nav-menu-item-ancestor-active-color)',
    navMenuCurrentListGapDefault: '0',
    navMenuCurrentNestedGapDefault: '0',
    navMenuCurrentCollapseOffsetTopDefault: '0',
    navMenuCurrentGroupPaddingLeftDefault:
      'calc(var(--vf-nav-menu-leading-icon-column-size) + var(--vf-nav-menu-item-gap))',
    navMenuPillsGroupPaddingLeft:
      'calc(var(--vf-field-input-padding-start-with-leading-md) + var(--vf-nav-menu-leading-icon-column-size) + var(--vf-nav-menu-item-gap))',
    tableOfContentsPillsListGap: 'var(--vf-table-of-contents-list-gap)',
    tableOfContentsPillsItemPadding: '0.25rem 0.625rem',
    tableOfContentsPillsItemMinHeight: '2rem',
    tableOfContentsPillsHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tableOfContentsPillsHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    tableOfContentsPillsActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    tableOfContentsPillsActiveBackground: 'var(--vf-color-background-surface-selected, var(--vf-color-primary-soft))',
    menuBarPillsSubmenuHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    menuBarPillsSubmenuActiveBackground: 'var(--vf-color-background-surface-selected, var(--vf-color-primary-soft))',
    menuBarPillsListGap: 'var(--vf-nav-menu-list-gap)',
    menuBarItemColor: 'var(--vf-selectable-color)',
    menuBarTopItemFontWeight: 'var(--vf-text-label-font-weight)',
    menuBarTopItemPaddingInline: 'var(--vf-surface-gap-compact)',
    menuBarItemFocusColor: 'var(--vf-color-selected-foreground, var(--vf-color-primary))',
    menuBarItemFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    menuBarItemAncestorActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    menuBarTopHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    menuBarTopHoverBackground: 'var(--vf-color-background-surface-hover, transparent)',
    menuBarTopActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    menuBarTopActiveBackground: 'var(--vf-color-background-surface-selected, transparent)',
    menuBarSubmenuHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    menuBarSubmenuHoverBackground: 'var(--vf-color-background-surface-hover, transparent)',
    menuBarSubmenuActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    menuBarSubmenuActiveBackground: 'var(--vf-color-background-surface-selected, transparent)',
    menuBarPillsTopHoverColor: 'var(--vf-nav-menu-pills-item-hover-color)',
    menuBarPillsTopHoverBackground: 'var(--vf-nav-menu-pills-item-hover-background)',
    menuBarPillsTopActiveColor: 'var(--vf-nav-menu-pills-item-active-color)',
    menuBarPillsTopActiveBackground: 'var(--vf-nav-menu-pills-item-active-background)',
    menuBarPillsTopOpenColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    menuBarPillsTopOpenBackground: 'var(--vf-color-background-surface-selected, var(--vf-color-primary-soft))',
    menuBarPillsSubmenuHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    menuBarPillsSubmenuActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    menuBarPillsSubmenuOpenColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    menuBarPillsSubmenuOpenBackground: 'var(--vf-color-background-surface-selected, var(--vf-color-primary-soft))',
    menuBarSubmenuOffsetInline: '0.75rem',
    menuBarGroupLetterSpacing: '0.06em',
    menuBarExternalIconOffsetY: '-0.02em',
    menuBarCurrentListGapDefault: '0',
    tableOfContentsFocusColor: 'var(--vf-color-selected-foreground, var(--vf-color-primary))',
    tableOfContentsFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    tableOfContentsCurrentListGapDefault: '0',
    dropdownItemColor: 'var(--vf-selectable-color)',
    dropdownItemFocusColor: 'var(--vf-color-selected-foreground, var(--vf-color-primary))',
    dropdownItemFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    dropdownItemDefaultHoverColor: 'var(--vf-nav-menu-item-hover-color)',
    dropdownItemDefaultHoverBackground: 'var(--vf-nav-menu-item-hover-background)',
    dropdownItemDefaultActiveColor: 'var(--vf-nav-menu-item-active-color)',
    dropdownItemDefaultActiveBackground: 'var(--vf-nav-menu-item-active-background)',
    dropdownItemPillsHoverColor: 'var(--vf-nav-menu-pills-item-hover-color)',
    dropdownItemPillsHoverBackground: 'var(--vf-nav-menu-pills-item-hover-background)',
    dropdownItemPillsActiveColor: 'var(--vf-nav-menu-pills-item-active-color)',
    dropdownItemPillsActiveBackground: 'var(--vf-nav-menu-pills-item-active-background)',
    breadcrumbsLinkColor: 'var(--vf-color-text-link, var(--vf-selectable-color))',
    breadcrumbsLinkHoverColor: 'var(--vf-color-text-link-hover, var(--vf-color-text))',
    breadcrumbsLinkFocusColor: 'var(--vf-color-text-link, var(--vf-color-primary))',
    breadcrumbsCurrentColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    breadcrumbsDisabledColor: 'var(--vf-color-text-disabled, var(--vf-selectable-color))',
    breadcrumbsSeparatorColor: 'var(--vf-color-icon-secondary, var(--vf-selectable-color))',
    accordionBorderColor: 'var(--vf-color-border-default, var(--vf-color-border))',
    accordionBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    accordionColor: 'var(--vf-selectable-color)',
    accordionTriggerExpandedColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    accordionTriggerHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    accordionTriggerFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    accordionIconColor: 'var(--vf-color-icon-secondary, var(--vf-color-muted))',
    accordionContentBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    accordionContentBorderColor: 'var(--vf-color-border-divider, var(--vf-color-border))',
    accordionContentColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    tabsListBorderColor: 'var(--vf-color-border-divider, var(--vf-color-border))',
    tabsTabColor: 'var(--vf-selectable-color)',
    tabsTabHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tabsTabActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    tabsTabDisabledColor: 'var(--vf-color-text-disabled, var(--vf-color-muted))',
    tabsIndicatorColor: 'var(--vf-color-selected-foreground, var(--vf-color-primary))',
    tabsIndicatorHeight: '3px',
    tabsListBackground: 'transparent',
    tabsListPaddingBottom: '3px',
    tabsTabBackground: 'transparent',
    tabsTabHoverBackground: 'var(--vf-color-background-surface-hover, transparent)',
    tabsTabActiveBackground: 'var(--vf-color-background-surface-selected, transparent)',
    tabsListBaselineOverlap: '1px',
    tabsScrollButtonWidth: '1.75rem',
    tabsScrollButtonIconOffsetY: '-3px',
    tabsFadeWidth: '2rem',
    tabsScrollbarHeight: '0.375rem',
    tabsGapOffset: '0.25rem',
    tabsFocusRingColor: 'var(--vf-color-focus-ring)',
    tabsPanelColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tabsPanelFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    horizontalScrollerIconSizeDefault: '1em',
    horizontalScrollerControlIconSize: '1.25em',
    avatarBackground: 'var(--vf-color-background-surface-subtle, var(--vf-color-surface-muted))',
    avatarColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    avatarRadius: 'var(--vf-radius-control-tight)',
    avatarSizeSm: '1.75rem',
    avatarSizeMd: '2.25rem',
    avatarSizeLg: '2.5rem',
    avatarFontSizeSm: 'var(--vf-font-size-xs)',
    avatarFontSizeMd: 'var(--vf-font-size-xl)',
    avatarFontSizeLg: 'var(--vf-font-size-3xl)',
    avatarIconSize: '1em',
    badgeBackground: 'var(--vf-color-background-surface-subtle, var(--vf-color-surface-muted))',
    badgeBorderColor: 'var(--vf-color-border-default, var(--vf-color-border))',
    badgeColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    badgePrimaryBackground: 'var(--vf-color-interactive-primary-subtle-background, var(--vf-color-primary-soft))',
    badgePrimaryBorderColor: 'var(--vf-color-interactive-primary-border, var(--vf-color-primary))',
    badgePrimaryColor: 'var(--vf-color-interactive-primary-subtle-foreground, var(--vf-color-primary))',
    badgeSuccessBackground: 'var(--vf-color-status-success-subtle-background, var(--vf-color-success-soft))',
    badgeSuccessBorderColor: 'var(--vf-color-status-success-border, var(--vf-color-success))',
    badgeSuccessColor: 'var(--vf-color-status-success-subtle-foreground, var(--vf-color-success))',
    badgeInfoBackground: 'var(--vf-color-status-info-subtle-background, var(--vf-color-info-soft))',
    badgeInfoBorderColor: 'var(--vf-color-status-info-border, var(--vf-color-info))',
    badgeInfoColor: 'var(--vf-color-status-info-subtle-foreground, var(--vf-color-info))',
    badgeWarnBackground: 'var(--vf-color-status-warning-subtle-background, var(--vf-color-warn-soft))',
    badgeWarnBorderColor: 'var(--vf-color-status-warning-border, var(--vf-color-warn))',
    badgeWarnColor: 'var(--vf-color-status-warning-subtle-foreground, var(--vf-color-warn))',
    badgeHelpBackground: 'var(--vf-color-status-help-subtle-background, var(--vf-color-help-soft))',
    badgeHelpBorderColor: 'var(--vf-color-status-help-border, var(--vf-color-help))',
    badgeHelpColor: 'var(--vf-color-status-help-subtle-foreground, var(--vf-color-help))',
    badgeDangerBackground: 'var(--vf-color-status-danger-subtle-background, var(--vf-color-danger-soft))',
    badgeDangerBorderColor: 'var(--vf-color-status-danger-border, var(--vf-color-danger))',
    badgeDangerColor: 'var(--vf-color-status-danger-subtle-foreground, var(--vf-color-danger))',
    badgeLetterSpacing: '0.01em',
    badgeContrastBackground: 'var(--vf-color-background-inverse-subtle, var(--vf-color-contrast-soft))',
    badgeContrastBorderColor: 'var(--vf-color-border-inverse, var(--vf-color-contrast))',
    badgeContrastColor: 'var(--vf-color-text-primary, var(--vf-color-contrast))',
    tagBackground: 'var(--vf-color-background-surface-subtle, var(--vf-color-surface-muted))',
    tagBorderColor: 'var(--vf-color-border-default, var(--vf-color-border))',
    tagColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tagPrimaryBorderColor: 'var(--vf-color-interactive-primary-border, var(--vf-color-primary))',
    tagPrimaryColor: 'var(--vf-color-interactive-primary-subtle-foreground, var(--vf-color-primary))',
    tagSuccessBorderColor: 'var(--vf-color-status-success-border, var(--vf-color-success))',
    tagSuccessColor: 'var(--vf-color-status-success-subtle-foreground, var(--vf-color-success))',
    tagInfoBorderColor: 'var(--vf-color-status-info-border, var(--vf-color-info))',
    tagInfoColor: 'var(--vf-color-status-info-subtle-foreground, var(--vf-color-info))',
    tagWarnBorderColor: 'var(--vf-color-status-warning-border, var(--vf-color-warn))',
    tagWarnColor: 'var(--vf-color-status-warning-subtle-foreground, var(--vf-color-warn))',
    tagHelpBorderColor: 'var(--vf-color-status-help-border, var(--vf-color-help))',
    tagHelpColor: 'var(--vf-color-status-help-subtle-foreground, var(--vf-color-help))',
    tagDangerBorderColor: 'var(--vf-color-status-danger-border, var(--vf-color-danger))',
    tagDangerColor: 'var(--vf-color-status-danger-subtle-foreground, var(--vf-color-danger))',
    tagContrastBorderColor: 'var(--vf-color-border-inverse, var(--vf-color-contrast))',
    tagContrastColor: 'var(--vf-color-text-primary, var(--vf-color-contrast))',
    tagLetterSpacing: '0.01em',
    alertColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    alertBodyColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    alertPrimaryIconColor: 'var(--vf-color-interactive-primary-subtle-foreground, var(--vf-color-primary))',
    alertSuccessBorderColor: 'var(--vf-color-status-success-border, var(--vf-color-success-border-soft))',
    alertSuccessBackground: 'var(--vf-color-status-success-subtle-background, var(--vf-color-success-soft))',
    alertSuccessIconColor: 'var(--vf-color-status-success-icon, var(--vf-color-success))',
    alertInfoBorderColor: 'var(--vf-color-status-info-border, var(--vf-color-info-border-soft))',
    alertInfoBackground: 'var(--vf-color-status-info-subtle-background, var(--vf-color-info-soft))',
    alertInfoIconColor: 'var(--vf-color-status-info-icon, var(--vf-color-info))',
    alertWarnBorderColor: 'var(--vf-color-status-warning-border, var(--vf-color-warn-border-soft))',
    alertWarnBackground: 'var(--vf-color-status-warning-subtle-background, var(--vf-color-warn-soft))',
    alertWarnIconColor: 'var(--vf-color-status-warning-icon, var(--vf-color-warn))',
    alertHelpBorderColor: 'var(--vf-color-status-help-border, var(--vf-color-help-border-soft))',
    alertHelpBackground: 'var(--vf-color-status-help-subtle-background, var(--vf-color-help-soft))',
    alertHelpIconColor: 'var(--vf-color-status-help-icon, var(--vf-color-help))',
    alertDangerBorderColor: 'var(--vf-color-status-danger-border, var(--vf-color-danger-border-soft))',
    alertDangerBackground: 'var(--vf-color-status-danger-subtle-background, var(--vf-color-danger-soft))',
    alertDangerIconColor: 'var(--vf-color-status-danger-icon, var(--vf-color-danger))',
    alertContrastBorderColor: 'var(--vf-color-border-inverse, var(--vf-color-contrast-border-soft))',
    alertContrastBackground: 'var(--vf-color-background-inverse-subtle, var(--vf-color-contrast-soft))',
    alertContrastIconColor: 'var(--vf-color-icon-primary, var(--vf-color-contrast))',
    alertBoxShadow: '0 1px 2px color-mix(in srgb, var(--vf-color-text-primary, var(--vf-color-text)) 4%, transparent)',
    alertContentMaxWidth: '68ch',
    progressBarHeight: '0.5rem',
    progressBarRadius: '999px',
    progressBarTrackBackground: 'var(--vf-color-background-surface-disabled, var(--vf-color-surface-muted))',
    progressBarLabelFontSize: '0.625rem',
    progressBarValueColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    progressBarLabelColor: 'var(--vf-color-interactive-primary-foreground, var(--vf-color-primary-contrast))',
    progressBarTransitionDuration: '160ms',
    progressBarTransitionEasing: 'ease',
    progressBarIndeterminateDuration: '2.1s',
    progressBarIndeterminateLongEasing: 'cubic-bezier(0.65, 0.815, 0.735, 0.395)',
    progressBarIndeterminateShortEasing: 'cubic-bezier(0.165, 0.84, 0.44, 1)',
    progressBarIndeterminateShortDelay: '1.15s',
    progressBarLabelPaddingInline: '0.25rem',
    progressBarStripedAngle: '135deg',
    progressBarStripedSegmentSize: '0.5rem',
    progressBarStripedSize: '1.4375rem',
    progressBarStripedTintRatio: '82%',
    progressBarStripedAnimationDuration: '900ms',
    progressSpinnerSize: '2rem',
    asyncSkeletonMinHeight: '120px',
    progressSpinnerTrackColor: 'var(--vf-color-background-surface-disabled, var(--vf-color-surface-muted))',
    progressSpinnerValueColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    progressSpinnerDuration: '1.4s',
    progressSpinnerRotateEasing: 'linear',
    progressSpinnerDashEasing: 'ease-in-out',
    progressSpinnerInlineTrackColor: 'color-mix(in srgb, currentColor 30%, transparent)',
    progressSpinnerInlineValueColor: 'currentColor',
    skeletonBackground: 'var(--vf-color-background-surface-disabled, var(--vf-color-surface-muted))',
    skeletonShimmerBackground: 'color-mix(in srgb, var(--vf-color-text-primary, var(--vf-color-text)) 6%, transparent)',
    skeletonShimmerDuration: '1.2s',
    skeletonShimmerEasing: 'ease',
    skeletonShimmerIterationCount: 'infinite',
    skeletonShimmerStartX: '-100%',
    skeletonShimmerEndX: '100%',
    skeletonGateFadeDurationDefault: '220ms',
    skeletonGateFadeEasingDefault: 'ease',
    skeletonGateOverflowDefault: 'hidden',
    dividerColor: 'var(--vf-color-border-divider, var(--vf-color-border))',
    cardBorderColor: 'var(--vf-color-border-default, var(--vf-color-border))',
    cardBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    cardColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    cardBodyColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    panelBorderColor: 'var(--vf-color-border-default, var(--vf-color-border))',
    panelBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    panelColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    panelSubtleBackground: 'transparent',
    tableBorderColor: 'var(--vf-color-border-divider, var(--vf-color-border))',
    tableBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    tableColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tableCaptionColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    tableHeadBackground: 'var(--vf-color-background-surface-subtle, var(--vf-color-surface-muted))',
    tableHeadColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tableFootBackground: 'var(--vf-color-background-surface-subtle, var(--vf-color-surface-muted))',
    tableFootColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    tableStripeBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    dialogContentBorderColor: 'var(--vf-color-border-strong, var(--vf-color-border))',
    dialogContentBackground: 'var(--vf-color-background-surface-elevated, var(--vf-color-surface))',
    dialogContentColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    dialogContentFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    dialogDividerColor: 'var(--vf-divider-color)',
    dialogHeaderMinHeight: '4rem',
    dialogFooterMinHeight: '4rem',
    commandPaletteFocusRingColor: 'var(--vf-color-focus-ring)',
    commandPaletteActionColor: 'var(--vf-color-icon-secondary, var(--vf-color-muted))',
    commandPaletteMutedColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    commandPaletteItemTextColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    drawerContentBorderColor: 'var(--vf-color-border-strong, var(--vf-color-border))',
    drawerContentBackground: 'var(--vf-color-background-surface-elevated, var(--vf-color-surface))',
    drawerContentColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    drawerContentFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    drawerDividerColor: 'var(--vf-divider-color)',
    drawerHeaderMinHeight: '4rem',
    drawerFooterMinHeight: '4rem',
    popoverTriggerFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    popoverContentBorderColor: 'var(--vf-color-border-strong, var(--vf-color-border))',
    popoverContentBackground: 'var(--vf-color-background-surface-elevated, var(--vf-color-surface))',
    popoverContentColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tooltipContentBorderColor: 'var(--vf-color-border-inverse, var(--vf-color-border))',
    tooltipContentBackground: 'var(--vf-color-background-inverse, var(--vf-color-surface))',
    tooltipContentColor: 'var(--vf-color-text-inverse, var(--vf-color-text))',
    textBodyFontSize: 'var(--vf-font-size-xl)',
    textBodyLineHeight: 'var(--vf-line-height-normal)',
    textBodyFontWeight: 'var(--vf-font-weight-regular)',
    textCaptionFontSize: 'var(--vf-font-size-sm)',
    textCaptionLineHeight: 'var(--vf-line-height-normal)',
    textCaptionFontWeight: 'var(--vf-font-weight-medium)',
    textLabelFontSize: 'var(--vf-font-size-md)',
    textLabelLineHeight: 'var(--vf-line-height-tight)',
    textLabelFontWeight: 'var(--vf-font-weight-medium)',
    headingFontSizeSm: 'var(--vf-font-size-lg)',
    headingFontSizeMd: 'var(--vf-font-size-xl)',
    headingFontSizeLg: 'var(--vf-font-size-2xl)',
    headingFontSizeXl: 'var(--vf-font-size-3xl)',
    headingFontWeight: 'var(--vf-font-weight-semibold)',
    headingH1FontSize: '1.875rem',
    headingH1LineHeight: '1.2',
    headingH2FontSize: '1.625rem',
    headingH2LineHeight: '1.25',
    headingH3FontSize: '1.4375rem',
    headingH3LineHeight: '1.3',
    headingH4FontSize: '1.1875rem',
    headingH4LineHeight: '1.35',
    headingH5FontSize: '1.0625rem',
    headingH5LineHeight: '1.4',
    headingH6FontSize: 'var(--vf-font-size-md)',
    headingH6LineHeight: '1.45',
    textLinkBorderWidth: '1px',
    textLinkUnderlineThickness: '1px',
    textLinkUnderlineOffset: '0.2em',
    textLinkTransitionDuration: '0.18s',
    textLinkTransitionEasing: 'ease',
    textLinkHoverColor: 'var(--vf-color-text-link-hover, var(--vf-color-primary))',
    textCodePaddingBlock: '0.125rem',
    textCodePaddingInline: '0.375rem',
    textCodeBorderWidth: '1px',
    listDiscPaddingInlineStart: '1.25rem',
    listDecimalPaddingInlineStart: '1.375rem',
    listItemGap: '0.375rem',
    blockquotePaddingBlock: '0.125rem',
    blockquotePaddingInlineStart: '0.875rem',
    blockquoteBorderWidth: '3px',
    proseFlowGap: '0.75rem',
    buttonSecondaryHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    buttonSecondaryHoverBorderColor: 'var(--vf-color-border-interactive, var(--vf-color-border))',
    buttonSecondaryActiveBackground: 'var(--vf-color-background-surface-active, var(--vf-color-surface-muted))',
    buttonSecondaryActiveBorderColor: 'var(--vf-color-border-strong, var(--vf-color-border))',
    buttonGhostHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    buttonGhostHoverBorderColor: 'transparent',
    buttonGhostActiveBackground: 'var(--vf-color-background-surface-active, var(--vf-color-surface-muted))',
    buttonGhostActiveBorderColor: 'transparent',
    buttonSolidHoverFilter: 'none',
    buttonSolidActiveFilter: 'none',
    fieldBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    fieldBorderColor: 'var(--vf-color-border-interactive, var(--vf-color-border))',
    fieldHoverBorderColor: 'var(--vf-color-interactive-primary-border, var(--vf-color-primary))',
    fieldFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    fieldInvalidBorderColor: 'var(--vf-color-status-danger-border, var(--vf-color-danger))',
    fieldDisabledBackground: 'var(--vf-color-background-surface-disabled, var(--vf-color-surface-muted))',
    fieldDisabledColor: 'var(--vf-color-text-disabled, var(--vf-color-muted))',
    fieldPlaceholderColor: 'var(--vf-color-text-placeholder, var(--vf-color-muted))',
    fieldsetLegendColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    fieldsetDescriptionColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    fieldsetErrorColor: 'var(--vf-color-status-danger-subtle-foreground, var(--vf-color-danger))',
    inputBackground: 'var(--vf-field-background)',
    inputBorderColor: 'var(--vf-field-border-color)',
    inputHoverBorderColor: 'var(--vf-field-hover-border-color)',
    inputFocusBorderColor: 'var(--vf-field-focus-border-color)',
    inputInvalidBorderColor: 'var(--vf-field-invalid-border-color)',
    inputDisabledBackground: 'var(--vf-field-disabled-background)',
    inputColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    inputDisabledColor: 'var(--vf-field-disabled-color)',
    inputPlaceholderColor: 'var(--vf-field-placeholder-color)',
    textareaBackground: 'var(--vf-field-background)',
    textareaBorderColor: 'var(--vf-field-border-color)',
    textareaHoverBorderColor: 'var(--vf-field-hover-border-color)',
    textareaFocusBorderColor: 'var(--vf-field-focus-border-color)',
    textareaInvalidBorderColor: 'var(--vf-field-invalid-border-color)',
    textareaDisabledBackground: 'var(--vf-field-disabled-background)',
    textareaColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    textareaDisabledColor: 'var(--vf-field-disabled-color)',
    textareaPlaceholderColor: 'var(--vf-field-placeholder-color)',
    selectBackground: 'var(--vf-field-background)',
    selectBorderColor: 'var(--vf-field-border-color)',
    selectHoverBorderColor: 'var(--vf-field-hover-border-color)',
    selectFocusBorderColor: 'var(--vf-field-focus-border-color)',
    selectInvalidBorderColor: 'var(--vf-field-invalid-border-color)',
    selectDisabledBackground: 'var(--vf-field-disabled-background)',
    selectColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    selectDisabledColor: 'var(--vf-field-disabled-color)',
    selectPlaceholderColor: 'var(--vf-field-placeholder-color)',
    selectIconColor: 'var(--vf-color-icon-secondary, var(--vf-color-muted))',
    selectDisabledIconColor: 'var(--vf-field-disabled-color)',
    selectOptionColor: 'var(--vf-selectable-color)',
    selectOptionHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    selectOptionHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    selectOptionFocusColor: 'var(--vf-selectable-active-color)',
    selectOptionActiveColor: 'var(--vf-selectable-active-color)',
    selectOptionActiveBackground: 'var(--vf-selectable-active-background)',
    selectOptionDisabledColor: 'var(--vf-field-disabled-color)',
    selectionControlBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    selectionControlBorderColor: 'var(--vf-color-border-interactive, var(--vf-color-border))',
    selectionControlHoverBorderColor: 'var(--vf-field-hover-border-color)',
    selectionControlFocusBorderColor: 'var(--vf-color-border-focus, var(--vf-color-primary))',
    selectionControlInvalidBorderColor: 'var(--vf-color-status-danger-border, var(--vf-color-danger))',
    selectionControlDisabledBackground: 'var(--vf-color-background-surface-disabled, var(--vf-color-surface-muted))',
    selectionControlDisabledBorderColor: 'var(--vf-color-border-disabled, var(--vf-color-border))',
    selectionControlDisabledColor: 'var(--vf-color-text-disabled, var(--vf-color-muted))',
    checkboxBackground: 'var(--vf-selection-control-background)',
    checkboxBorderColor: 'var(--vf-selection-control-border-color)',
    checkboxHoverBorderColor: 'var(--vf-selection-control-hover-border-color)',
    checkboxFocusBorderColor: 'var(--vf-selection-control-focus-border-color)',
    checkboxInvalidBorderColor: 'var(--vf-selection-control-invalid-border-color)',
    checkboxCheckedBackground: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    checkboxCheckedBorderColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    checkboxMarkColor: 'var(--vf-color-interactive-primary-foreground, var(--vf-color-primary-contrast))',
    checkboxDisabledBackground: 'var(--vf-selection-control-disabled-background)',
    checkboxDisabledBorderColor: 'var(--vf-selection-control-disabled-border-color)',
    checkboxDisabledColor: 'var(--vf-selection-control-disabled-color)',
    checkboxDisabledMarkColor: 'var(--vf-selection-control-disabled-color)',
    radioControlBackground: 'var(--vf-selection-control-background)',
    radioHoverBorderColor: 'var(--vf-selection-control-hover-border-color)',
    radioBorderColor: 'var(--vf-selection-control-border-color)',
    radioFocusBorderColor: 'var(--vf-selection-control-focus-border-color)',
    radioInvalidBorderColor: 'var(--vf-selection-control-invalid-border-color)',
    radioCheckedBorderColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    radioDotColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    radioDisabledBackground: 'var(--vf-selection-control-disabled-background)',
    radioDisabledBorderColor: 'var(--vf-selection-control-disabled-border-color)',
    radioDisabledColor: 'var(--vf-selection-control-disabled-color)',
    radioDisabledDotColor: 'var(--vf-selection-control-disabled-color)',
    switchTrackBorderColor: 'var(--vf-selection-control-border-color)',
    switchTrackHoverBorderColor: 'var(--vf-selection-control-hover-border-color)',
    switchTrackFocusBorderColor: 'var(--vf-selection-control-focus-border-color)',
    switchTrackCheckedBorderColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    switchTrackCheckedHoverBorderColor: 'var(--vf-color-interactive-primary-hover-background, var(--vf-color-primary))',
    switchTrackInvalidBorderColor: 'var(--vf-selection-control-invalid-border-color)',
    switchTrackStaticBorderColor: 'var(--vf-selection-control-border-color)',
    switchTrackDisabledBackground: 'var(--vf-selection-control-disabled-background)',
    switchTrackDisabledBorderColor: 'var(--vf-selection-control-disabled-border-color)',
    switchDisabledColor: 'var(--vf-selection-control-disabled-color)',
    switchTrackBackground: 'var(--vf-radio-control-background)',
    switchTrackHoverBackground: 'var(--vf-color-background-surface-hover, var(--vf-color-surface-muted))',
    switchTrackCheckedBackground: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    switchTrackCheckedHoverBackground: 'var(--vf-color-interactive-primary-hover-background, var(--vf-color-primary))',
    switchThumbBackground: 'var(--vf-color-icon-secondary, var(--vf-color-text))',
    switchThumbBorderColor: 'var(--vf-switch-thumb-background)',
    switchThumbShadow: 'none',
    switchThumbColor: 'var(--vf-color-icon-inverse, var(--vf-color-surface))',
    switchThumbIconSize: '0.75rem',
    switchThumbDisabledBackground: 'var(--vf-switch-thumb-background)',
    switchThumbDisabledBorderColor: 'var(--vf-switch-thumb-disabled-background)',
    switchThumbDisabledColor: 'var(--vf-switch-thumb-color)',
    switchThumbCheckedBackground: 'var(--vf-color-interactive-primary-foreground, var(--vf-color-surface))',
    switchThumbCheckedBorderColor: 'var(--vf-switch-thumb-checked-background)',
    switchThumbCheckedShadow: 'none',
    switchThumbCheckedColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    switchThumbInverseBackground: 'var(--vf-color-background-inverse, var(--vf-color-surface))',
    switchThumbInverseBorderColor: 'var(--vf-color-border-inverse, var(--vf-color-border))',
    switchThumbInverseColor: 'var(--vf-color-icon-inverse, var(--vf-color-text))',
    proseHeadingMargin: '1.5rem',
    proseHeadingGap: '0.5em',
    proseBlockSpacing: '1em',
    proseListPaddingInlineStart: '1.5em',
    proseListItemSpacing: '0.375em',
    proseLinkHoverColor: 'var(--vf-color-text-link-hover, var(--vf-color-primary))',
    proseBlockquotePaddingInlineStart: '1rem',
    proseBlockquoteBorderWidth: '3px',
    proseInlineCodeFontSize: 'var(--vf-font-size-md)',
    proseInlineCodePadding: '0.0625rem 0.375rem',
    proseCodeBlockPadding: '0.75rem 1rem',
    proseHrBorderWidth: '1px',
    proseHrOpacity: '0.72',
    proseHrMargin: '1.5rem',
    ...legacyLightColorTokens,
    focusRingWidth: '3px',
    radius: '0.75rem',
    radiusControl: 'calc(var(--vf-radius) - 0.125rem)',
    radiusControlTight: 'calc(var(--vf-radius) - 0.25rem)',
    radiusSurface: 'var(--vf-radius)',
    radiusOverlay: 'calc(var(--vf-radius) + 0.125rem)',
    ...breakpointTokens,
    controlHeightSm: '1.75rem',
    controlHeightMd: '2.25rem',
    controlHeightLg: '2.5rem',
    controlFontSizeSm: 'var(--vf-text-label-font-size)',
    controlFontSizeMd: 'var(--vf-text-body-font-size)',
    controlFontSizeLg: 'var(--vf-font-size-2xl)',
    controlLineHeight: 'var(--vf-text-label-line-height)',
    fieldIconSize: '1rem',
    fieldIconSizeSm: '0.9375rem',
    fieldIconSizeLg: '1.0625rem',
    fieldAdornmentOffsetSm: '0.5rem',
    fieldAdornmentOffsetMd: '0.625rem',
    fieldAdornmentOffsetLg: '0.625rem',
    fieldLeadingIconOffsetSm: 'var(--vf-field-adornment-offset-sm)',
    fieldLeadingIconOffsetMd: 'var(--vf-field-adornment-offset-md)',
    fieldLeadingIconOffsetLg: 'var(--vf-field-adornment-offset-lg)',
    fieldTrailingBeforeClearOffsetSm: '2rem',
    fieldTrailingBeforeClearOffsetMd: '2.25rem',
    fieldTrailingBeforeClearOffsetLg: '2.375rem',
    fieldClearButtonSizeSm: '1.25rem',
    fieldClearButtonSizeMd: '1.375rem',
    fieldClearButtonSizeLg: 'var(--vf-icon-size-xl)',
    fieldInputPaddingStartWithLeadingSm: '1.875rem',
    fieldInputPaddingStartWithLeadingMd: '2.125rem',
    fieldInputPaddingStartWithLeadingLg: '2.25rem',
    fieldInputPaddingEndWithTrailingSm: '1.875rem',
    fieldInputPaddingEndWithTrailingMd: '2.125rem',
    fieldInputPaddingEndWithTrailingLg: '2.25rem',
    fieldInputPaddingEndWithTrailingAndClearSm: '3.25rem',
    fieldInputPaddingEndWithTrailingAndClearMd: '3.625rem',
    fieldInputPaddingEndWithTrailingAndClearLg: '3.875rem',
    fieldSelectPaddingStartWithLeadingSm: '0.5rem',
    fieldSelectPaddingStartWithLeadingMd: '0.75rem',
    fieldSelectPaddingStartWithLeadingLg: '0.875rem',
    fieldSelectPaddingEndWithClearSm: '2rem',
    fieldSelectPaddingEndWithClearMd: '2.25rem',
    fieldSelectPaddingEndWithClearLg: '2.375rem',
    buttonPaddingSm: '0.25rem 0.5rem',
    buttonPaddingMd: '0.3125rem 0.75rem',
    buttonPaddingLg: '0.5rem 1rem',
    buttonGap: '0.5rem',
    buttonIconSizeSm: 'var(--vf-icon-size-sm)',
    buttonIconSizeMd: 'var(--vf-icon-size-md)',
    buttonIconSizeLg: 'var(--vf-icon-size-lg)',
    fieldPaddingBlockSm: '0.25rem',
    fieldPaddingBlockMd: '0.3125rem',
    fieldPaddingBlockLg: '0.5rem',
    fieldPaddingInlineSm: '0.5rem',
    fieldPaddingInlineMd: '0.75rem',
    fieldPaddingInlineLg: '0.875rem',
    fieldPaddingSm: 'var(--vf-field-padding-block-sm) var(--vf-field-padding-inline-sm)',
    fieldPaddingMd: 'var(--vf-field-padding-block-md) var(--vf-field-padding-inline-md)',
    fieldPaddingLg: 'var(--vf-field-padding-block-lg) var(--vf-field-padding-inline-lg)',
    fieldFloatingLabelOffsetBlockDefault: '50%',
    fieldFloatingLabelTranslateYDefault: '-50%',
    fieldFloatingLabelRestingOffsetBlockSmDefault: '50%',
    fieldFloatingLabelRestingOffsetBlockMdDefault: '50%',
    fieldFloatingLabelRestingOffsetBlockLgDefault: '50%',
    fieldFloatingLabelActiveOffsetBlockDefault: '0.25rem',
    fieldFloatingLabelActiveTranslateYDefault: '0',
    fieldFloatingInLabelActiveOffsetBlock: '0.25rem',
    fieldFloatingInLabelActiveTranslateY: '0',
    fieldFloatingInLabelBackground: 'transparent',
    fieldFloatingInControlPaddingTopSm: '1rem',
    fieldFloatingInControlPaddingBottomSm: '0.125rem',
    fieldFloatingInControlPaddingTopMd: '1.3125rem',
    fieldFloatingInControlPaddingBottomMd: '0.1875rem',
    fieldFloatingInControlPaddingTopLg: '1.625rem',
    fieldFloatingInControlPaddingBottomLg: '0.375rem',
    fieldFloatingInTextareaPaddingTopSm: '1.5rem',
    fieldFloatingInTextareaPaddingTopMd: '1.625rem',
    fieldFloatingInTextareaPaddingTopLg: '1.625rem',
    fieldFloatingOnLabelActiveOffsetBlock: '0',
    fieldFloatingOnLabelActiveTranslateY: '-50%',
    fieldFloatingOnControlPaddingTopSm: 'var(--vf-field-padding-block-sm)',
    fieldFloatingOnControlPaddingBottomSm: 'var(--vf-field-padding-block-sm)',
    fieldFloatingOnControlPaddingTopMd: 'var(--vf-field-padding-block-md)',
    fieldFloatingOnControlPaddingBottomMd: 'var(--vf-field-padding-block-md)',
    fieldFloatingOnControlPaddingTopLg: 'var(--vf-field-padding-block-lg)',
    fieldFloatingOnControlPaddingBottomLg: 'var(--vf-field-padding-block-lg)',
    fieldFloatingOnTextareaPaddingTopSm: 'calc(var(--vf-field-padding-block-sm) + 0.125rem)',
    fieldFloatingOnTextareaPaddingTopMd: 'calc(var(--vf-field-padding-block-md) + 0.125rem)',
    fieldFloatingOnTextareaPaddingTopLg: 'calc(var(--vf-field-padding-block-lg) + 0.125rem)',
    fieldFloatingOnPaddingTop: '0.375rem',
    fieldFloatingOnActivePaddingInline: '0.25rem',
    fieldFloatingOverLabelActiveOffsetBlock: '-0.0625rem',
    fieldFloatingOverLabelActiveTranslateY: '-100%',
    fieldFloatingOverLabelBackground: 'transparent',
    fieldFloatingOverControlPaddingTopSm: 'var(--vf-field-padding-block-sm)',
    fieldFloatingOverControlPaddingBottomSm: 'var(--vf-field-padding-block-sm)',
    fieldFloatingOverControlPaddingTopMd: 'var(--vf-field-padding-block-md)',
    fieldFloatingOverControlPaddingBottomMd: 'var(--vf-field-padding-block-md)',
    fieldFloatingOverControlPaddingTopLg: 'var(--vf-field-padding-block-lg)',
    fieldFloatingOverControlPaddingBottomLg: 'var(--vf-field-padding-block-lg)',
    fieldFloatingOverTextareaPaddingTopSm: 'var(--vf-field-padding-block-sm)',
    fieldFloatingOverTextareaPaddingTopMd: 'var(--vf-field-padding-block-md)',
    fieldFloatingOverTextareaPaddingTopLg: 'var(--vf-field-padding-block-lg)',
    fieldFloatingOverPaddingTop: '0.6875rem',
    fieldFloatingControlOffsetInlineSm: 'calc(var(--vf-field-padding-inline-sm) + 1px)',
    fieldFloatingControlOffsetInlineMd: 'calc(var(--vf-field-padding-inline-md) + 1px)',
    fieldFloatingControlOffsetInlineLg: 'calc(var(--vf-field-padding-inline-lg) + 1px)',
    fieldFloatingInputOffsetInlineSm: 'calc(0.5rem + 1px)',
    fieldFloatingInputOffsetInlineMd: 'calc(0.75rem + 1px)',
    fieldFloatingInputOffsetInlineLg: 'calc(1rem + 1px)',
    fieldFloatingInputSmActiveOffsetBlock: '0.125rem',
    fieldPasswordToggleClearGap: '0.5rem',
    fieldPasswordToggleBeforeClearGap: '0.375rem',
    fieldFloatingSelectPaddingAdjustmentSm: '0.0625rem',
    fieldFloatingSelectPaddingAdjustmentLg: '0.0625rem',
    fieldFloatingInputSmMinHeight: 'calc(var(--vf-control-height-sm) + 0.125rem)',
    fieldFloatingInputSmPaddingTop: '1.3125rem',
    fieldFloatingInputSmPaddingBottom: '0.125rem',
    fieldFloatingTextareaTranslateY: '0',
    fieldFloatingTextareaRestingOffsetBlockSm: 'calc(var(--vf-field-padding-block-sm) + 0.1875rem)',
    fieldFloatingTextareaRestingOffsetBlockMd: 'calc(var(--vf-field-padding-block-md) + 0.1875rem)',
    fieldFloatingTextareaRestingOffsetBlockLg: 'calc(var(--vf-field-padding-block-lg) + 0.3125rem)',
    checkboxSizeSm: 'var(--vf-icon-size-lg)',
    checkboxSizeMd: '1.25rem',
    checkboxSizeLg: '1.375rem',
    selectionGap: 'var(--vf-surface-gap)',
    checkboxControlOffsetSm: '0.0938rem',
    checkboxControlOffsetMd: '0.125rem',
    checkboxControlOffsetLg: '0.0625rem',
    checkboxMarkWidth: '0.25rem',
    checkboxMarkHeight: '0.5rem',
    checkboxMarkWidthSm: '0.2188rem',
    checkboxMarkHeightSm: '0.4375rem',
    checkboxMarkWidthLg: '0.3125rem',
    checkboxMarkHeightLg: '0.625rem',
    checkboxMarkStrokeWidth: '2px',
    checkboxMarkOffsetY: '-0.0625rem',
    checkboxRadiusAdjustment: '0.0625rem',
    radioDotSize: '0.5rem',
    radioDotSizeSm: '0.4375rem',
    radioDotSizeLg: '0.5625rem',
    radioControlOffsetSm: '0.0938rem',
    radioControlOffsetMd: '0.125rem',
    radioControlOffsetLg: '0.0625rem',
    switchWidthSm: '2.125rem',
    switchWidthMd: '2.375rem',
    switchWidthLg: '2.625rem',
    switchHeightSm: '1.25rem',
    switchHeightMd: '1.375rem',
    switchHeightLg: '1.5rem',
    switchThumbSizeSm: 'var(--vf-icon-size-sm)',
    switchThumbSizeMd: '1rem',
    switchThumbSizeLg: 'var(--vf-icon-size-lg)',
    switchThumbInset: '0.125rem',
    switchControlOffsetSm: '0.0313rem',
    switchControlOffsetMd: '0.0625rem',
    switchControlOffsetLg: '0',
    switchThumbIconSizeSm: '0.625rem',
    switchThumbIconSizeLg: '0.875rem',
    textareaMinHeightSm: '4.5rem',
    textareaMinHeightMd: '6rem',
    textareaMinHeightLg: '7rem',
    overlayPadding: 'var(--vf-surface-padding)',
    overlayGap: 'var(--vf-surface-gap)',
    overlayViewportPadding: 'var(--vf-surface-padding)',
    overlayFloatShadow:
      '0 var(--vf-menu-gap) calc(var(--vf-overlay-padding) * 0.625) color-mix(in srgb, var(--vf-palette-neutral-1000) 16%, transparent), 0 var(--vf-overlay-border-width) calc(var(--vf-menu-gap) / 2) color-mix(in srgb, var(--vf-palette-neutral-1000) 10%, transparent)',
    menuPadding: 'var(--vf-surface-gap-compact)',
    menuGap: '0.25rem',
    menuMinWidth: 'calc(var(--vf-breakpoint-xs) * 0.4)',
    selectMenuMaxHeight: 'min(13rem, 38vh)',
    selectFilterMinHeightSm: 'calc(var(--vf-control-height-sm) + 0.5rem)',
    surfacePadding: '1rem',
    surfaceGap: '0.75rem',
    surfacePaddingCompact: '0.75rem',
    surfaceGapCompact: '0.5rem',
    sectionPadding: '0.75rem 1rem',
    sectionGap: '0.75rem',
    stepperMarkerSize: 'calc(var(--vf-control-height-md) - 0.125rem)',
    stepperRailSize: '2px',
    stepperRailColor: 'var(--vf-color-border-divider, var(--vf-color-border))',
    stepperProgressColor: 'var(--vf-color-interactive-primary-subtle-foreground, var(--vf-color-primary))',
    stepperTriggerColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    stepperMarkerBackground: 'var(--vf-color-background-surface, var(--vf-color-surface))',
    stepperMarkerBorderColor: 'var(--vf-color-border-interactive, var(--vf-color-border))',
    stepperMarkerColor: 'var(--vf-color-icon-secondary, var(--vf-color-muted))',
    stepperLabelColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    stepperDescriptionColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    stepperCompleteMarkerBackground: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    stepperCompleteMarkerBorderColor: 'var(--vf-color-interactive-primary-background, var(--vf-color-primary))',
    stepperCompleteMarkerColor: 'var(--vf-color-interactive-primary-foreground, var(--vf-color-primary-contrast))',
    stepperCompleteLabelColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    stepperCompleteDescriptionColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    stepperCurrentMarkerBackground:
      'var(--vf-color-interactive-primary-subtle-background, var(--vf-color-primary-soft))',
    stepperCurrentMarkerBorderColor: 'var(--vf-color-interactive-primary-border, var(--vf-color-primary))',
    stepperCurrentMarkerColor: 'var(--vf-color-interactive-primary-subtle-foreground, var(--vf-color-primary))',
    stepperCurrentLabelColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    stepperCurrentDescriptionColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    stepperUpcomingLabelColor: 'var(--vf-color-text-muted, var(--vf-color-muted))',
    stepperUpcomingDescriptionColor: 'var(--vf-color-text-muted, var(--vf-color-muted))',
    stepperDisabledColor: 'var(--vf-color-text-disabled, var(--vf-color-muted))',
    stepperFocusRingColor: 'var(--vf-color-focus-ring)',
    stepperHorizontalTriggerRowGap: 'calc(var(--vf-surface-gap-compact) + 0.125rem)',
    stepperContentPaddingTop: '0.125rem',
    stepperContentGap: '0.125rem',
    stepperCurrentMarkerBoxShadow:
      '0 0 0 2px var(--vf-color-interactive-primary-subtle-background, var(--vf-color-primary-soft))',
    dataTableSkeletonCellMaxInlineSize: '12rem',
    dataTableLoadingSpinnerSize: 'var(--vf-progress-spinner-size)',
    dataTableStateColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    dataTablePaginationColor: 'var(--vf-color-text-secondary, var(--vf-color-muted))',
    dataTablePaginationPageColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tabsGap: 'var(--vf-surface-gap)',
    tabsListGap: 'var(--vf-menu-gap)',
    tabsListPadding: 'var(--vf-menu-gap)',
    tabsTabPaddingInline: 'var(--vf-surface-gap)',
    tabsPanelPaddingTop: 'var(--vf-surface-gap)',
    navMenuListGap: 'var(--vf-menu-gap)',
    navMenuNestedGap: 'var(--vf-menu-gap)',
    navMenuCollapseOffsetTop: 'var(--vf-menu-gap)',
    navMenuCollapseInsetLevel0Margin: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetLevel0Padding: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetSimpleLevel0Margin: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetSimpleLevel0Padding: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetDeepMargin: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetDeepPadding: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetSimpleDeepMargin: 'var(--vf-surface-gap-compact)',
    navMenuCollapseInsetSimpleDeepPadding: 'var(--vf-surface-gap-compact)',
    navMenuNodeGroupSpacing: 'var(--vf-menu-gap)',
    navMenuGroupPadding: 'calc(var(--vf-menu-gap) * 1.5) var(--vf-surface-gap)',
    navMenuGroupFontSize: 'var(--vf-text-label-font-size)',
    navMenuGroupLabelLetterSpacing: '0.06em',
    navMenuItemPadding: '0.25rem 0',
    navMenuItemGap: 'var(--vf-surface-gap-compact)',
    navMenuLeadingIconSize: 'var(--vf-icon-size-md)',
    navMenuLeadingIconColumnSize: 'calc(var(--vf-icon-size-md) * 1.25)',
    tableOfContentsGap: 'var(--vf-menu-gap)',
    tableOfContentsListGap: 'var(--vf-nav-menu-list-gap)',
    tableOfContentsTitleFontSize: 'var(--vf-text-caption-font-size)',
    tableOfContentsTitleColor: 'var(--vf-color-text-muted, var(--vf-color-muted))',
    tableOfContentsItemPadding: 'var(--vf-menu-gap) 0',
    tableOfContentsLevelStep:
      'calc(var(--vf-nav-menu-collapse-inset-simple-level-0-margin) + var(--vf-nav-menu-collapse-inset-simple-level-0-padding))',
    tableMinWidth: 'var(--vf-dialog-width-md)',
    tableOfContentsColor: 'var(--vf-selectable-color)',
    tableOfContentsHoverColor: 'var(--vf-color-text-primary, var(--vf-color-text))',
    tableOfContentsHoverBackground: 'var(--vf-color-background-surface-hover, transparent)',
    tableOfContentsActiveColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    tableOfContentsActiveBackground: 'var(--vf-color-background-surface-selected, transparent)',
    badgeHeight: '1.375rem',
    badgePadding: '0.0625rem 0.25rem',
    badgeGap: 'var(--vf-menu-gap)',
    badgeRadius: 'var(--vf-radius-control-tight)',
    badgeFontSize: 'var(--vf-text-label-font-size)',
    badgeLineHeight: 'var(--vf-text-label-line-height)',
    tagHeight: 'var(--vf-icon-size-xl)',
    tagPadding: '0.125rem 0.3125rem',
    tagFontSize: 'var(--vf-text-label-font-size)',
    tagLineHeight: 'var(--vf-text-label-line-height)',
    tooltipPadding: 'var(--vf-surface-gap-compact) var(--vf-surface-gap)',
    tooltipMaxWidth: '16rem',
    tooltipFontSize: 'var(--vf-text-body-font-size)',
    tooltipLineHeight: 'var(--vf-text-body-line-height)',
    dialogWidthSm: '28rem',
    dialogWidthMd: '36rem',
    dialogWidthLg: '48rem',
    dialogMaxHeight: 'min(85vh, 48rem)',
    drawerSizeSm: '20rem',
    drawerSizeMd: '26rem',
    drawerSizeLg: '32rem',
    drawerRadiusTopLeft: '0px',
    drawerRadiusTopRight: '0px',
    drawerRadiusBottomRight: '0px',
    drawerRadiusBottomLeft: '0px',
    drawerRoundedRadius: 'var(--vf-radius-overlay)',
    drawerOffsetTop: '0px',
    drawerViewportWidth: '100dvw',
    drawerOffsetXRest: '0',
    drawerOffsetYRest: '0',
    drawerOffsetXLeft: '-100%',
    drawerOffsetXRight: '100%',
    drawerOffsetYTop: '-100%',
    drawerOffsetYBottom: '100%',
    drawerBodyPadding: 'var(--vf-overlay-padding)',
    dialogTitleFontSize: 'var(--vf-text-body-font-size)',
    dialogHeaderGap: 'var(--vf-surface-gap)',
    dialogActionsGap: 'var(--vf-surface-gap-compact)',
    overlayFloatEnterScaleDefault: '0.97',
    overlayArrowOverlapOffsetDefault: 'calc(var(--vf-overlay-border-width) * -1)',
    overlayViewportBlockSizeDefault: '100dvh',
    commandPaletteItemIconSize: 'var(--vf-icon-size-md)',
    commandPaletteOffsetTopDefault: 'calc(var(--vf-overlay-viewport-padding) + var(--vf-control-height-sm))',
    commandPaletteEnterShiftDefault: 'calc(var(--vf-dialog-actions-gap) * -1)',
    commandPaletteItemContentGapDefault: 'calc(var(--vf-nav-menu-list-gap) * 0.75)',
    commandPaletteItemTitleIconOffsetYDefault: 'calc(var(--vf-focus-ring-width) / -3)',
    commandPaletteHintGapDefault: 'calc(var(--vf-nav-menu-item-gap) * 0.75)',
    commandPaletteHintIconPaddingInlineDefault: 'calc(var(--vf-nav-menu-list-gap) / 2)',
    commandPaletteHintIconSize: 'var(--vf-icon-size-sm)',
    popoverWidth: 'min(100vw - (var(--vf-overlay-padding) * 2), calc(var(--vf-breakpoint-xs) * 0.733333))',
    floatingArrowSize: '0.625rem',
    alertPrimarySoft: 'var(--vf-color-interactive-primary-subtle-background, var(--vf-color-primary-soft))',
    alertPrimaryBorderSoft: 'var(--vf-color-interactive-primary-border, var(--vf-color-primary-border-soft))',
    alertIconOffsetY: 'calc((var(--vf-text-body-line-height) - 1) * 0.5em)',
    alertContentGap: '0.25rem',
    alertTitleFontSize: 'var(--vf-text-body-font-size)',
    cardTitleFontSize: 'var(--vf-text-body-font-size)',
    panelTitleFontSize: 'var(--vf-text-body-font-size)',
    motionDurationFast: vfMotionTokens.durationFast,
    motionDurationNormal: vfMotionTokens.durationNormal,
    motionEaseStandard: vfMotionTokens.easeStandard,
    zOverlay: '1000',
    zDrawer: '1000',
    zDropdown: '1100',
    zPopover: '1125',
    zTooltip: '1150',
    spacing: '1rem',
    shadow: 'none',
  },
  dark: {
    ...legacyDarkColorTokens,
    fieldBackground: 'var(--vf-color-background-surface, var(--vf-color-bg))',
    switchThumbBackground: 'var(--vf-color-icon-secondary, var(--vf-color-text))',
    switchThumbBorderColor: 'var(--vf-switch-thumb-background)',
    switchThumbColor: 'var(--vf-color-icon-inverse, var(--vf-color-surface))',
    switchThumbCheckedBackground: 'var(--vf-color-interactive-primary-foreground, var(--vf-color-surface))',
    switchThumbCheckedBorderColor: 'var(--vf-switch-thumb-checked-background)',
    switchThumbCheckedColor: 'var(--vf-color-selected-foreground, var(--vf-color-text))',
    switchThumbInverseBackground: 'var(--vf-color-background-inverse, var(--vf-color-contrast))',
    switchThumbInverseBorderColor: 'var(--vf-color-border-inverse, var(--vf-color-contrast))',
    switchThumbInverseColor: 'var(--vf-color-icon-inverse, var(--vf-color-contrast-contrast))',
    focusRingWidth: '3px',
    zOverlay: '1000',
    zDrawer: '1000',
    zDropdown: '1100',
    zPopover: '1125',
    zTooltip: '1150',
    shadow: 'none',
  },
} satisfies LegacyDefaultThemePreset;

export const defaultThemePresetSource = {
  name: legacyDefaultThemePresetSource.name,
  tokens: {
    ...legacyDefaultThemePresetSource.tokens,
    ...primitiveColorTokens,
    ...semanticLightColorTokens,
  },
  dark: {
    ...legacyDefaultThemePresetSource.dark,
    ...semanticDarkColorTokens,
  },
} satisfies CompleteDefaultThemePreset;
