import type { VfLayoutPreset } from "./types";

export const defaultLayoutsPreset: VfLayoutPreset = {
  name: "vueforge-layouts",
  tokens: {
    shellSidebarWidth: "18rem",
    shellAsideWidth: "20rem",
    shellSidebarCollapsedWidth: "4.5rem",
    shellHeaderHeight: "4rem",
    viewportHeight: "100vh",
    minWidth: "20rem",
    sizeZero: "0",
    sizeOne: "1",
    sizeHalf: "50%",
    sizeFull: "100%",
    spaceLayoutBase: "var(--vf-surface-padding)",
    spaceLayoutRoomy: "calc(var(--vf-layout-space-layout-base) * 1.5)",
    shellAreaPaddingBlock: "var(--vf-layout-space-layout-base)",
    shellAreaPaddingInline: "var(--vf-layout-space-layout-base)",
    containerMaxWidth: "80rem",
    containerPadding: "var(--vf-surface-padding)",
    sectionInsetDefault: "var(--vf-surface-padding)",
    sectionRadius: "var(--vf-layout-radius-base)",
    sectionShadow: "var(--vf-layout-surface-shadow)",
    gridMinItemWidth: "16rem",
    radiusBase: "var(--vf-radius-surface)",
    borderBase: "1px solid var(--vf-color-border)",
    surfaceBase: "var(--vf-color-surface)",
    surfaceMuted: "var(--vf-color-surface-muted)",
    surfaceSubtle:
      "color-mix(in srgb, var(--vf-layout-surface-base) 70%, transparent)",
    surfaceRadius: "var(--vf-layout-radius-base)",
    surfaceShadow: "var(--vf-layout-shadow-overlay)",
    shadowOverlay: "var(--vf-shadow)",
    appBackground: "var(--vf-layout-surface-muted)",
    headerBackground: "var(--vf-layout-surface-base)",
    headerBorder: "var(--vf-layout-border-base)",
    headerHeight: "var(--vf-layout-shell-header-height)",
    headerPaddingBlock: "var(--vf-layout-shell-area-padding-block)",
    headerPaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    subheaderHeight: "2.75rem",
    subheaderPaddingBlock: "0.375rem",
    subheaderPaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    sidebarBackground: "var(--vf-layout-surface-base)",
    sidebarBorder: "var(--vf-layout-border-base)",
    sidebarPaddingBlock: "var(--vf-layout-shell-area-padding-block)",
    sidebarPaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    contentBackground: "var(--vf-layout-surface-base)",
    contentPaddingBlock: "var(--vf-layout-shell-area-padding-block)",
    contentPaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    contentSubheaderBackground: "var(--vf-layout-header-background)",
    contentSubheaderBorder: "var(--vf-layout-header-border)",
    contentSubheaderHeight: "var(--vf-layout-subheader-height)",
    contentSubheaderPaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    asideBackground: "var(--vf-layout-surface-base)",
    asideBorder: "var(--vf-layout-border-base)",
    asidePaddingBlock: "var(--vf-layout-shell-area-padding-block)",
    asidePaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    footerBackground: "var(--vf-layout-surface-base)",
    footerBorder: "var(--vf-layout-border-base)",
    footerPaddingBlock: "var(--vf-layout-shell-area-padding-block)",
    footerPaddingInline: "var(--vf-layout-shell-area-padding-inline)",
    appShellHeaderStickyZIndex: "20",
    appShellSubheaderStickyZIndex: "19",
    appShellContentSubheaderStickyZIndex: "18",
    documentLayoutHeaderStickyZIndex: "20",
    documentLayoutSubheaderStickyZIndex: "19",
    documentLayoutContentSubheaderStickyZIndex: "18",
    documentLayoutEdgeNotchColor: "var(--vf-color-border)",
    documentLayoutEdgeNotchWidth: "7px",
    documentLayoutEdgeNotchHeight: "5px",
    documentLayoutEdgeNotchOffset: "0.5px",
    errorLayoutPaddingBlock: "calc(var(--vf-layout-space-layout-roomy) * 2)",
    errorLayoutPanelPadding: "calc(var(--vf-layout-space-layout-roomy) * 1.5)",
    errorLayoutCodeFontSize: "clamp(2.25rem, 8vw, 5.5rem)",
    errorLayoutCodeFontWeight: "700",
    errorLayoutCodeLineHeight: "1",
    errorLayoutCodeLetterSpacing: "-0.04em",
    errorLayoutTitleFontSize: "clamp(1.375rem, 3vw, 2rem)",
    errorLayoutTitleLineHeight: "1.2",
    errorLayoutDescriptionColor: "var(--vf-color-muted)",
    errorLayoutDescriptionLineHeight: "1.5"
  }
};
