export default {
    gap: '0.75rem',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    headerGap: '0.75rem',
    headerPadding: '0.75rem 0.9rem',
    headerFontSize: '0.95rem',
    headerFontWeight: '600',
    headerTextColor: 'var(--vf-text-color)',
    headerBackgroundColor: 'var(--vf-bg-color)',
    headerHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    headerActiveBackgroundColor: 'var(--vf-bg-soft-color)',
    contentPadding: '0.75rem 0.9rem',
    contentTextColor: 'var(--vf-text-color)',
    contentBackgroundColor: 'var(--vf-bg-color)',
    iconSize: '1rem',
    iconColor: 'var(--vf-secondary-text-color)',
    dividerColor: 'var(--vf-divider-color)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        headerPadding: '0.5rem 0.75rem',
        headerFontSize: '0.875rem',
        contentPadding: '0.5rem 0.75rem',
    },
    large: {
        headerPadding: '0.9rem 1.1rem',
        headerFontSize: '1rem',
        contentPadding: '0.9rem 1.1rem',
    },
};
