export default {
    gap: '0',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    sidebarBackgroundColor: 'var(--vf-bg-color)',
    sidebarBorderColor: 'var(--vf-border-color)',
    headerHeight: '3.25rem',
    headerPadding: '0.75rem 1rem',
    headerGap: '0.75rem',
    headerBackgroundColor: 'var(--vf-bg-color)',
    headerBorderColor: 'var(--vf-border-color)',
    contentPadding: '1rem',
    mainBackgroundColor: 'var(--vf-bg-color)',
    footerPadding: '0.75rem 1rem',
    footerBorderColor: 'var(--vf-border-color)',
    footerBackgroundColor: 'var(--vf-bg-color)',
    toggleSize: '2rem',
    toggleBorderRadius: 'var(--vf-radii-md)',
    toggleBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.1)',
    toggleTextColor: 'var(--vf-text-color)',
    toggleHoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.16)',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.34)',
    zIndex: '110',
};
