export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    dividerColor: 'var(--vf-border-color)',
    headerBackgroundColor: 'var(--vf-gray-100)',
    fontSize: '0.875rem',
    cellPadding: '0.75rem',
    eventFontWeight: '600',
    metaColor: 'var(--vf-secondary-text-color)',
    metaFontSize: '0.75rem',
    actionColor: 'var(--vf-primary-color)',
    actionFontSize: '0.8125rem',
    detailsGap: '1rem',
    sectionTitleFontSize: '0.875rem',
    monoFontFamily:
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    monoFontSize: '0.75rem',
};
