export default {
    gap: '0.75rem',
    padding: '0.75rem 0.9rem',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    iconColor: 'currentColor',
    fontSize: '0.95rem',
    lineHeight: '1.4',
    bodyGap: '0.2rem',
    titleFontSize: '0.95rem',
    titleFontWeight: '600',
    actionsGap: '0.5rem',
    closeSize: '1.5rem',
    closeRadius: 'var(--vf-radii-sm)',
    closeFontSize: '1rem',
    closeHoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.12)',
    stickyTop: '0',
    zIndex: '115',
    info: {
        backgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.1)',
        borderColor: 'rgba(var(--vf-blue-600-rgb), 0.4)',
        textColor: 'var(--vf-text-color)',
    },
    success: {
        backgroundColor: 'rgba(var(--vf-green-600-rgb), 0.12)',
        borderColor: 'rgba(var(--vf-green-600-rgb), 0.45)',
        textColor: 'var(--vf-text-color)',
    },
    warn: {
        backgroundColor: 'rgba(var(--vf-yellow-600-rgb), 0.16)',
        borderColor: 'rgba(var(--vf-yellow-600-rgb), 0.5)',
        textColor: 'var(--vf-text-color)',
    },
    danger: {
        backgroundColor: 'rgba(var(--vf-red-600-rgb), 0.12)',
        borderColor: 'rgba(var(--vf-red-600-rgb), 0.45)',
        textColor: 'var(--vf-text-color)',
    },
};
