export default {
    height: '3.8rem',
    padding: '0.45rem 0.7rem calc(0.45rem + env(safe-area-inset-bottom))',
    gap: '0.35rem',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    zIndex: '125',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    itemMinHeight: '2.5rem',
    itemPadding: '0.35rem 0.5rem',
    itemBorderRadius: 'var(--vf-radii-sm)',
    itemContentGap: '0.15rem',
    itemColor: 'var(--vf-secondary-text-color)',
    itemHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    itemActiveBackgroundColor: 'var(--vf-color-blue-100)',
    itemActiveColor: 'var(--vf-color-blue-700)',
    iconSize: '1rem',
    labelFontSize: '0.75rem',
    badgeTextColor: '#ffffff',
    badgeBackgroundColor: 'var(--vf-color-red-500)',
};
