export default {
    gap: '0.75rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-lg)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    slideMinHeight: '12rem',
    slidePadding: '1rem',
    transitionDuration: '320ms',
    transitionEasing: 'ease',
    arrowSize: '2.25rem',
    arrowSizeMobile: '1.875rem',
    arrowOffset: '0.6rem',
    arrowBorderColor: 'var(--vf-border-color)',
    arrowBorderRadius: '999px',
    arrowBackgroundColor: 'var(--vf-bg-soft-color)',
    arrowTextColor: 'var(--vf-text-color)',
    indicatorsGap: '0.45rem',
    indicatorSize: '0.6rem',
    indicatorBorderColor: 'var(--vf-border-color)',
    indicatorBackgroundColor: 'var(--vf-bg-soft-color)',
    indicatorActiveBorderColor: 'var(--vf-color-blue)',
    indicatorActiveBackgroundColor: 'var(--vf-color-blue)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    focusBorderColor: 'var(--vf-color-blue)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
