export default {
    gap: '0.6rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.7rem',
    headerGap: '0.6rem',
    metaFontSize: '0.75rem',
    metaColor: 'var(--vf-secondary-text-color)',
    surfaceBorderColor: 'var(--vf-border-color)',
    surfaceBorderRadius: 'var(--vf-radii-sm)',
    surfaceBackgroundColor: 'var(--vf-bg-color)',
    minHeight: '14rem',
    stateMinHeight: '6rem',
    stateColor: 'var(--vf-secondary-text-color)',
    stateFontSize: '0.8125rem',
    darkBorderColor: 'rgba(var(--vf-gray-400-rgb), 0.4)',
    darkBackgroundColor: '#0f172a',
    darkTextColor: '#e2e8f0',
    darkSurfaceBorderColor: 'rgba(var(--vf-gray-400-rgb), 0.35)',
    darkSurfaceBackgroundColor: '#0b1220',
    darkMetaColor: '#93a4bf',
    darkStateColor: '#93a4bf',
    disabledOpacity: '0.65',
};
