export default {
    gap: '0',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: '#f8fbff',
    textColor: '#0f172a',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.8125rem',
    lineHeight: '1.5',
    padding: '0.75rem 0.9rem',
    headerGap: '0.75rem',
    headerPadding: '0.55rem 0.75rem',
    headerBorderColor: 'rgba(148, 163, 184, 0.28)',
    metaGap: '0.55rem',
    metaColor: '#475569',
    metaFontSize: '0.75rem',
    filenameColor: '#0f172a',
    filenameFontWeight: '600',
    actionsGap: '0.45rem',
    actionBorderColor: 'rgba(148, 163, 184, 0.38)',
    actionBorderRadius: 'var(--vf-radii-sm)',
    actionBackgroundColor: '#ffffff',
    actionTextColor: '#0f172a',
    actionPadding: '0.2rem 0.55rem',
    actionFontSize: '0.75rem',
    lineGap: '0.7rem',
    lineNumberColor: '#64748b',
    lineNumberMinWidth: '2.1rem',
    darkBorderColor: 'rgba(148, 163, 184, 0.35)',
    darkBackgroundColor: '#0a1425',
    darkTextColor: '#e2e8f0',
    darkHeaderBorderColor: 'rgba(148, 163, 184, 0.35)',
    darkMetaColor: '#93a4bf',
    darkFilenameColor: '#e2e8f0',
    darkActionBorderColor: 'rgba(148, 163, 184, 0.45)',
    darkActionBackgroundColor: 'rgba(15, 23, 42, 0.7)',
    darkActionTextColor: '#e2e8f0',
    darkLineNumberColor: '#64748b',
    tokenKeywordColor: '#8b2fc9',
    tokenStringColor: '#0f7b45',
    tokenNumberColor: '#c2410c',
    tokenCommentColor: '#64748b',
    tokenVariableColor: '#0f4c81',
    tokenTagColor: '#0f4c81',
    tokenSelectorColor: '#0f4c81',
    tokenComponentColor: '#0369a1',
    tokenAttributeColor: '#7c3aed',
    tokenDirectiveColor: '#a21caf',
    tokenIdentifierColor: '#0369a1',
    tokenFunctionColor: '#1d4ed8',
    tokenPropertyColor: '#6d28d9',
    tokenOperatorColor: '#be185d',
    darkTokenKeywordColor: '#c084fc',
    darkTokenStringColor: '#86efac',
    darkTokenNumberColor: '#fca5a5',
    darkTokenCommentColor: '#94a3b8',
    darkTokenVariableColor: '#bfdbfe',
    darkTokenTagColor: '#93c5fd',
    darkTokenSelectorColor: '#93c5fd',
    darkTokenComponentColor: '#67e8f9',
    darkTokenAttributeColor: '#c4b5fd',
    darkTokenDirectiveColor: '#f0abfc',
    darkTokenIdentifierColor: '#7dd3fc',
    darkTokenFunctionColor: '#93c5fd',
    darkTokenPropertyColor: '#a5b4fc',
    darkTokenOperatorColor: '#f0abfc',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
