export default {
    gap: '0.75rem',
    itemGap: '0.75rem',
    indentSize: '1rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    padding: '0.75rem',
    resolvedBackgroundColor: 'var(--vf-green-100)',
    resolvedBorderColor: 'var(--vf-green-300)',
    metaGap: '0.5rem',
    authorFontWeight: '600',
    metaColor: 'var(--vf-secondary-text-color)',
    metaFontSize: '0.75rem',
    actionsGap: '0.75rem',
    actionColor: 'var(--vf-primary-color)',
    actionFontSize: '0.8125rem',
    replyMinHeight: '4.5rem',
    replyBorderColor: 'var(--vf-border-color)',
    replyBorderRadius: 'var(--vf-radii-sm)',
    replyBackgroundColor: 'var(--vf-bg-color)',
    disabledOpacity: '0.5',
};
