export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    fontSize: 'var(--vf-typography-font-size)',
    textColor: 'var(--vf-text-color)',
    headerBackgroundColor: 'var(--vf-bg-soft-color)',
    headerTextColor: 'var(--vf-text-color)',
    headerFontSize: 'var(--vf-typography-font-size)',
    headerFontWeight: '600',
    headerBorderColor: 'var(--vf-divider-color)',
    headerGap: '0.35rem',
    rowBackgroundColor: 'var(--vf-bg-color)',
    rowTextColor: 'var(--vf-text-color)',
    rowBorderColor: 'var(--vf-divider-color)',
    cellPadding: '0.6rem 0.75rem',
    stripedBackgroundColor: 'var(--vf-bg-soft-color)',
    hoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.06)',
    sortIconColor: 'var(--vf-secondary-text-color)',
    sortIconActiveColor: 'var(--vf-blue-600)',
    sortIconSize: '0.8rem',
    statePadding: '1rem',
    stateTextColor: 'var(--vf-secondary-text-color)',
    small: {
        fontSize: 'var(--vf-sizes-sm-font-size)',
        cellPadding: '0.45rem 0.6rem',
    },
    large: {
        fontSize: 'var(--vf-sizes-lg-font-size)',
        cellPadding: '0.75rem 0.9rem',
    },
};
