export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.6rem 0.75rem 0.75rem',
    legendPadding: '0 0.3rem',
    legendFontSize: '0.95rem',
    legendFontWeight: '600',
    legendColor: 'var(--vf-text-color)',
    contentPadding: '0.25rem 0',
    headerGap: '0.6rem',
    actionsGap: '0.5rem',
    toggleSize: '1.6rem',
    toggleRadius: 'var(--vf-radii-sm)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-text-color)',
    toggleHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
