export default {
    minHeight: '2.75rem',
    fontSize: 'var(--vf-typography-font-size)',
    gap: '0.75rem',
    padding: '0.5rem 0.6rem',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    hoverBorderColor: 'var(--vf-blue-500)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    dragBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.06)',
    listGap: '0.35rem',
    itemPadding: '0.35rem 0.45rem',
    itemBorderColor: 'var(--vf-border-color)',
    itemBackgroundColor: 'var(--vf-bg-color)',
    itemRadius: 'var(--vf-radii-sm)',
    itemTextColor: 'var(--vf-text-color)',
    sizeTextColor: 'var(--vf-secondary-text-color)',
    buttonPadding: '0.35rem 0.75rem',
    buttonRadius: 'var(--vf-radii-sm)',
    buttonBorderColor: 'var(--vf-border-color)',
    buttonBackgroundColor: 'var(--vf-bg-color)',
    buttonTextColor: 'var(--vf-text-color)',
    buttonHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    removeSize: '1.4rem',
    removeRadius: 'var(--vf-radii-sm)',
    removeHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    small: {
        padding: '0.35rem 0.5rem',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        buttonPadding: '0.25rem 0.6rem',
    },
    large: {
        padding: '0.65rem 0.75rem',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        buttonPadding: '0.45rem 0.9rem',
    },
};
