export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.6rem',
    stageGap: '0.6rem',
    maxHeight: '28rem',
    imageRadius: 'var(--vf-radii-sm)',
    imageBackgroundColor: 'var(--vf-bg-soft-color)',
    captionGap: '0.4rem',
    captionFontSize: '0.875rem',
    captionColor: 'var(--vf-secondary-text-color)',
    navSize: '2rem',
    navBorderColor: 'var(--vf-border-color)',
    navBackgroundColor: 'var(--vf-bg-color)',
    navTextColor: 'var(--vf-text-color)',
    indicatorsGap: '0.6rem',
    indicatorColor: 'var(--vf-border-color)',
    indicatorActiveColor: 'var(--vf-color-blue)',
    thumbnailsGap: '0.7rem',
    thumbnailsItemGap: '0.45rem',
    thumbnailSize: '3.2rem',
    thumbnailRadius: 'var(--vf-radii-sm)',
    thumbnailBorderColor: 'var(--vf-border-color)',
    thumbnailActiveBorderColor: 'var(--vf-color-blue)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
