export default {
    gap: '0.5rem',
    sentinelMinHeight: '2.5rem',
    sentinelPadding: '0.25rem 0',
    textColor: 'var(--vf-text-muted-color)',
    fontSize: '0.875rem',
    loadingColor: 'var(--vf-primary-color)',
    errorColor: 'var(--vf-danger-color)',
    endColor: 'var(--vf-text-muted-color)',
    disabledOpacity: '0.7',
    hintWidth: '2.2rem',
    hintHeight: '0.22rem',
    hintColor: 'rgba(var(--vf-gray-600-rgb), 0.35)',
    retryBorderColor: 'var(--vf-border-color)',
    retryRadius: '0.5rem',
    retryBackgroundColor: 'var(--vf-bg-color)',
    retryTextColor: 'var(--vf-text-color)',
    retryPadding: '0.35rem 0.7rem',
    retryFontSize: '0.8125rem',
    retryHoverBackgroundColor: 'rgba(var(--vf-gray-700-rgb), 0.08)',
    focusRingColor: 'rgba(var(--vf-primary-rgb), 0.32)',
};
