export default {
    gap: '0.5rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    actionsGap: '0.35rem',
    buttonPadding: '0.22rem 0.5rem',
    buttonRadius: 'var(--vf-radii-sm)',
    buttonBorderColor: 'var(--vf-border-color)',
    buttonBackgroundColor: 'var(--vf-controls-background-color)',
    buttonTextColor: 'var(--vf-text-color)',
    buttonHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    cancelButtonBackgroundColor: 'transparent',
    cancelButtonTextColor: 'var(--vf-secondary-text-color)',
    cancelButtonBorderColor: 'var(--vf-border-color)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        buttonPadding: '0.18rem 0.4rem',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        buttonPadding: '0.26rem 0.62rem',
    },
};
