export default {
    gap: '0.5rem',
    columnMinWidth: '17rem',
    columnGap: '0.75rem',
    columnBorderColor: 'var(--vf-border-color)',
    columnBorderRadius: 'var(--vf-radii-md)',
    columnBackgroundColor: 'var(--vf-bg-color)',
    columnHeaderPadding: '0.75rem',
    columnHeaderBorderColor: 'var(--vf-border-color)',
    columnTitleFontSize: '0.95rem',
    columnTitleFontWeight: '600',
    columnCountFontSize: '0.8rem',
    columnCountColor: 'var(--vf-secondary-text-color)',
    bodyPadding: '0.75rem',
    cardGap: '0.5rem',
    cardPadding: '0.75rem',
    cardBorderRadius: 'var(--vf-radii-md)',
    cardBorderColor: 'var(--vf-border-color)',
    cardBackgroundColor: 'var(--vf-bg-color)',
    cardHoverBorderColor: 'var(--vf-blue-600)',
    cardTitleFontSize: '0.9rem',
    cardTitleFontWeight: '600',
    cardDescriptionFontSize: '0.8125rem',
    cardDescriptionColor: 'var(--vf-secondary-text-color)',
    priorityLowColor: 'var(--vf-blue-600)',
    priorityMediumColor: 'var(--vf-yellow)',
    priorityHighColor: 'var(--vf-red)',
    tagGap: '0.35rem',
    tagPadding: '0.2rem 0.45rem',
    tagBorderRadius: '999px',
    tagBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.12)',
    tagTextColor: 'var(--vf-text-color)',
    assigneeFontSize: '0.75rem',
    assigneeColor: 'var(--vf-secondary-text-color)',
    emptyPadding: '0.75rem',
    emptyColor: 'var(--vf-secondary-text-color)',
    columnFooterPadding: '0.6rem 0.75rem',
    columnFooterBorderColor: 'var(--vf-border-color)',
    dragOpacity: '0.6',
};
