export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.35rem',
    minHeight: '2.5rem',
    maxHeight: '16rem',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    focusBorderColor: 'var(--vf-color-blue)',
    groupGapTop: '0.35rem',
    groupLabelPadding: '0.3rem 0.5rem',
    groupLabelColor: 'var(--vf-secondary-text-color)',
    groupLabelFontSize: '0.75rem',
    optionPadding: '0.5rem 0.65rem',
    optionBorderRadius: 'var(--vf-radii-sm)',
    optionHighlightedBackgroundColor: 'var(--vf-bg-soft-color)',
    optionSelectedBackgroundColor: 'rgba(var(--vf-blue-rgb), 0.12)',
    optionSelectedTextColor: 'var(--vf-text-color)',
    emptyPadding: '0.75rem',
    emptyColor: 'var(--vf-secondary-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        optionPadding: '0.4rem 0.55rem',
        fontSize: '0.875rem',
    },
    large: {
        optionPadding: '0.65rem 0.8rem',
        fontSize: '1rem',
    },
};
