export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    padding: '0.4rem 0.6rem',
    rootGap: '0.35rem',
    triggerTextColor: 'var(--vf-text-color)',
    triggerPadding: '0.45rem 0.65rem',
    triggerBorderRadius: 'var(--vf-radii-sm)',
    triggerActiveBackgroundColor: 'var(--vf-bg-soft-color)',
    panelOffset: '0.5rem',
    zIndex: '16',
    panelMinWidth: '28rem',
    panelBorderColor: 'var(--vf-border-color)',
    panelBorderRadius: 'var(--vf-radii-md)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelShadow: '0 12px 28px rgba(0, 0, 0, 0.14)',
    panelPadding: '0.85rem',
    columnsGap: '1rem',
    sectionTitleGap: '0.5rem',
    sectionTitleFontSize: '0.875rem',
    sectionTitleColor: 'var(--vf-secondary-text-color)',
    linkGap: '0.35rem',
    linkColor: 'var(--vf-text-color)',
    linkHoverColor: 'var(--vf-color-blue)',
};
