export default {
    controlMinHeight: '2.5rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.35rem 0.5rem',
    gap: '0.35rem',
    focusBorderColor: 'var(--vf-primary-color)',
    focusRingShadow: '0 0 0 2px rgba(var(--vf-primary-color-rgb), 0.2)',
    disabledOpacity: '0.5',
    chipGap: '0.35rem',
    chipBackgroundColor: 'var(--vf-gray-100)',
    chipBorderColor: 'var(--vf-border-color)',
    chipBorderRadius: 'var(--vf-radii-sm)',
    chipFontSize: '0.75rem',
    chipRemoveFontSize: '0.875rem',
    zIndex: '120',
    panelBorderColor: 'var(--vf-border-color)',
    panelBorderRadius: 'var(--vf-radii-md)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelShadow: '0 12px 24px rgba(0, 0, 0, 0.16)',
    panelMaxHeight: '18rem',
    optionPadding: '0.5rem 0.625rem',
    optionGap: '0.5rem',
    optionHighlightBackgroundColor: 'var(--vf-gray-100)',
    optionSelectedBackgroundColor: 'rgba(var(--vf-primary-color-rgb), 0.08)',
    optionTitleFontSize: '0.875rem',
    optionTitleFontWeight: '600',
    optionMetaFontSize: '0.75rem',
    optionMetaColor: 'var(--vf-secondary-text-color)',
    statePadding: '0.625rem',
};
