export default {
    width: '15rem',
    collapsedWidth: '4rem',
    padding: '0.5rem',
    gap: '0.5rem',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    toggleSize: '1.75rem',
    toggleRadius: 'var(--vf-radii-sm)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-text-color)',
    itemMinHeight: '2.5rem',
    itemPadding: '0.5rem 0.625rem',
    collapsedItemPadding: '0.5rem',
    itemBorderRadius: 'var(--vf-radii-sm)',
    itemGap: '0.25rem',
    itemContentGap: '0.5rem',
    itemColor: 'var(--vf-text-color)',
    itemHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    itemActiveBackgroundColor: 'var(--vf-color-blue-100)',
    itemActiveColor: 'var(--vf-color-blue-700)',
    iconSize: '1rem',
    labelFontSize: '0.875rem',
};
