export default {
    zIndex: '125',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.35)',
    top: '1rem',
    right: '1rem',
    width: '24rem',
    maxWidth: 'min(92vw, 24rem)',
    maxHeight: 'min(80vh, 36rem)',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-lg)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    shadow: '0 16px 40px rgba(0, 0, 0, 0.2)',
    dividerColor: 'var(--vf-border-color)',
    headerGap: '0.5rem',
    headerPadding: '0.75rem',
    titleGap: '0.4rem',
    titleFontSize: '1rem',
    titleLineHeight: '1.3',
    titleFontWeight: '600',
    badgeSize: '1.2rem',
    badgeBackgroundColor: 'var(--vf-blue-600)',
    badgeTextColor: 'var(--vf-white)',
    badgeFontSize: '0.75rem',
    actionsGap: '0.4rem',
    closeSize: '1.65rem',
    closeHoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.12)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    itemGap: '0.6rem',
    itemPadding: '0.7rem 0.75rem',
    unreadBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    avatarSize: '1.8rem',
    avatarBackgroundColor: 'var(--vf-gutter-color)',
    avatarTextColor: 'var(--vf-text-color)',
    avatarFontSize: '0.75rem',
    itemTitleFontSize: '0.9rem',
    itemTitleFontWeight: '600',
    itemMetaFontSize: '0.8125rem',
    itemMetaColor: 'var(--vf-secondary-text-color)',
    emptyPadding: '1rem',
    emptyColor: 'var(--vf-secondary-text-color)',
};
