export default {
    minHeight: '100vh',
    gap: '0',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    headerPadding: '0.75rem 1rem',
    headerBorderColor: 'var(--vf-border-color)',
    controlsGap: '0.5rem',
    contentPadding: '1rem',
    contentBackgroundColor: 'var(--vf-bg-color)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    footerPadding: '0.75rem 1rem',
    footerBorderColor: 'var(--vf-border-color)',
    toggleSize: '2rem',
    toggleBorderRadius: 'var(--vf-radii-md)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-text-color)',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.34)',
    zIndex: '110',
};
