export default {
    gap: '0.4rem',
    itemMinWidth: '2rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: '0.35rem 0.65rem',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    hoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    activeBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.28)',
    activeBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    activeTextColor: 'var(--vf-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    ellipsisPadding: '0.35rem 0.5rem',
    small: {
        fontSize: 'var(--vf-sizes-sm-font-size)',
        padding: '0.3rem 0.5rem',
    },
    large: {
        fontSize: 'var(--vf-sizes-lg-font-size)',
        padding: '0.45rem 0.8rem',
    },
};
