export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-lg)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    headerPadding: '0.75rem 0.85rem',
    bodyPadding: '0.85rem',
    footerPadding: '0.75rem 0.85rem',
    footerBorderColor: 'var(--vf-border-color)',
    headerGap: '0.75rem',
    titleFontSize: '1rem',
    titleFontWeight: '600',
    subtitleFontSize: '0.875rem',
    subtitleColor: 'var(--vf-secondary-text-color)',
    actionsGap: '0.5rem',
    toggleSize: '1.65rem',
    toggleRadius: 'var(--vf-radii-sm)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-text-color)',
    toggleHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        padding: '0.65rem 0.75rem',
        titleFontSize: '0.9rem',
    },
    large: {
        padding: '1rem 1.1rem',
        titleFontSize: '1.1rem',
    },
};
