export default {
    gap: '0.5rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    toggleSize: '1.5rem',
    toggleRadius: 'var(--vf-radii-sm)',
    toggleColor: 'var(--vf-secondary-text-color)',
    toggleHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    strengthGap: '0.5rem',
    strengthTrackHeight: '0.3rem',
    strengthTrackRadius: 'var(--vf-radii-sm)',
    strengthTrackBackgroundColor: 'var(--vf-gutter-color)',
    strengthWeakColor: 'var(--vf-red)',
    strengthMediumColor: 'var(--vf-yellow)',
    strengthStrongColor: 'var(--vf-green)',
    metaFontSize: '0.75rem',
    hintColor: 'var(--vf-secondary-text-color)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
    },
};
