export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    dividerColor: 'var(--vf-border-color)',
    headerBackgroundColor: 'var(--vf-gray-100)',
    stickyBackgroundColor: 'var(--vf-bg-color)',
    cellPadding: '0.625rem',
    labelFontSize: '0.875rem',
    labelFontWeight: '600',
    descriptionFontSize: '0.75rem',
    descriptionColor: 'var(--vf-secondary-text-color)',
    toggleMinWidth: '5.5rem',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBorderRadius: 'var(--vf-radii-sm)',
    togglePadding: '0.3rem 0.45rem',
    toggleBackgroundColor: 'transparent',
    toggleTextColor: 'var(--vf-text-color)',
    toggleFontSize: '0.75rem',
    allowBorderColor: 'var(--vf-green-300)',
    allowBackgroundColor: 'var(--vf-green-100)',
    allowTextColor: 'var(--vf-green-700)',
    denyBorderColor: 'var(--vf-red-300)',
    denyBackgroundColor: 'var(--vf-red-100)',
    denyTextColor: 'var(--vf-red-700)',
    disabledOpacity: '0.5',
};
