export default {
    gap: '0.75rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    headerColor: 'var(--vf-text-color)',
    listPadding: '0.45rem',
    listMinHeight: '14rem',
    itemPadding: '0.45rem 0.55rem',
    itemRadius: 'var(--vf-radii-sm)',
    itemHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    itemSelectedBackgroundColor: 'rgba(var(--vf-blue-rgb), 0.12)',
    itemSelectedColor: 'var(--vf-text-color)',
    focusRingColor: 'var(--vf-color-blue)',
    buttonBorderColor: 'var(--vf-border-color)',
    buttonRadius: 'var(--vf-radii-sm)',
    buttonBackgroundColor: 'var(--vf-bg-color)',
    buttonColor: 'var(--vf-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
