export default {
    gap: '0.5rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    minHeight: 'calc(var(--vf-controls-height) * 2.5)',
    resize: 'vertical',
    toolbarGap: '0.35rem',
    toolbarPadding: '0 0 0.5rem 0',
    toolbarBorderColor: 'var(--vf-divider-color)',
    toolbarBackgroundColor: 'transparent',
    toolbarButtonMinWidth: '2.4rem',
    toolbarButtonPadding: '0.2rem 0.45rem',
    toolbarButtonRadius: 'var(--vf-radii-sm)',
    toolbarButtonBorderColor: 'var(--vf-border-color)',
    toolbarButtonBackgroundColor: 'var(--vf-bg-color)',
    toolbarButtonTextColor: 'var(--vf-text-color)',
    toolbarButtonHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    toolbarButtonActiveBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.15)',
    counterFontSize: '0.75rem',
    counterColor: 'var(--vf-secondary-text-color)',
    counterDangerColor: 'var(--vf-red-600)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        toolbarButtonPadding: '0.15rem 0.35rem',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        toolbarButtonPadding: '0.3rem 0.55rem',
    },
};
