export default {
    gap: '0.75rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.75rem',
    titleFontSize: '0.95rem',
    titleFontWeight: '600',
    subtitleFontSize: '0.78rem',
    subtitleColor: 'var(--vf-secondary-text-color)',
    resourceWidth: '12rem',
    minTimelineWidth: '40rem',
    minGridWidth: '52rem',
    gridGap: '0.5rem',
    headBackgroundColor: 'var(--vf-gutter-color)',
    headBorderRadius: 'var(--vf-radii-sm)',
    headPadding: '0.45rem 0.55rem',
    headFontSize: '0.78rem',
    headFontWeight: '600',
    dividerColor: 'var(--vf-border-color)',
    slotMinWidth: '3.5rem',
    slotLabelFontSize: '0.72rem',
    slotLabelColor: 'var(--vf-secondary-text-color)',
    rowBorderRadius: 'var(--vf-radii-sm)',
    resourcePadding: '0.55rem',
    resourceBackgroundColor: 'var(--vf-bg-color)',
    resourceFontSize: '0.84rem',
    resourceFontWeight: '600',
    resourceMetaFontSize: '0.75rem',
    resourceMetaColor: 'var(--vf-secondary-text-color)',
    trackBackgroundColor: 'var(--vf-bg-color)',
    trackPadding: '0.35rem',
    trackGap: '0.35rem',
    slotHeight: '1.2rem',
    slotHoverBackgroundColor: 'rgba(var(--vf-primary-color-rgb), 0.08)',
    eventHeight: '1.875rem',
    eventBackgroundColor: 'var(--vf-primary-color)',
    eventTextColor: 'var(--vf-white)',
    eventBorderColor: 'rgba(var(--vf-primary-color-rgb), 0.6)',
    eventBorderRadius: '0.4rem',
    eventPadding: '0.15rem 0.3rem',
    eventFontSize: '0.7rem',
    eventTitleFontWeight: '600',
    eventTimeFontSize: '0.64rem',
    eventSelectedOutlineColor: 'var(--vf-text-color)',
};
