export default {
    gap: '0.5rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    iconSize: '0.8rem',
    iconColor: 'var(--vf-secondary-text-color)',
    clearSize: '1.15rem',
    clearRadius: 'var(--vf-radii-sm)',
    clearHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    loadingSize: '0.9rem',
    loadingBorderColor: 'var(--vf-border-color)',
    loadingTopBorderColor: 'var(--vf-blue-600)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        iconSize: '0.72rem',
        clearSize: '1rem',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        iconSize: '0.9rem',
        clearSize: '1.25rem',
    },
};
