export default {
    width: '100%',
    height: '1rem',
    lineHeight: '0.9rem',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-gutter-color)',
    shimmerColor: 'var(--vf-bg-color)',
    animationDuration: '2s',
    presetGap: '0.65rem',
    presetTableHeaderHeight: '1rem',
    presetTableRowHeight: '0.9rem',
    presetListAvatarSize: '2.5rem',
    presetListLineHeight: '0.8rem',
    presetListSecondaryWidth: '70%',
    presetFormLabelWidth: '35%',
    presetFormLabelHeight: '0.8rem',
    presetFormFieldHeight: '2.4rem',
};
