export default {
    width: '100%',
    gap: '0.5rem',
    textColor: 'var(--vf-text-color)',
    trackHeight: '0.35rem',
    trackBackgroundColor: 'var(--vf-gutter-color)',
    trackRadius: '999px',
    fillBackgroundColor: 'var(--vf-blue-600)',
    thumbSize: '1rem',
    thumbColor: '#ffffff',
    thumbBorderColor: 'var(--vf-blue-600)',
    thumbBorderWidth: '2px',
    thumbShadow: '0 1px 3px rgba(0, 0, 0, 0.25)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    markSize: '6px',
    markColor: 'var(--vf-border-color)',
    markLabelFontSize: '0.75rem',
    markLabelColor: 'var(--vf-secondary-text-color)',
    marksHeight: '1.25rem',
    valueFontSize: '0.875rem',
    valueColor: 'var(--vf-secondary-text-color)',
    small: {
        trackHeight: '0.25rem',
        thumbSize: '0.85rem',
        valueFontSize: '0.8rem',
    },
    large: {
        trackHeight: '0.5rem',
        thumbSize: '1.25rem',
        valueFontSize: '1rem',
    },
};
