export default {
    gap: '0.55rem',
    zIndex: '1400',
    offsetX: '1rem',
    offsetY: '1rem',
    offsetXMobile: '0.75rem',
    offsetYMobile: '0.75rem',
    transitionDuration: '220ms',
    transitionEasing: 'ease',
    triggerSize: '3rem',
    triggerPaddingX: '0.8rem',
    triggerBorderRadius: '999px',
    triggerBorderColor: 'var(--vf-border-color)',
    triggerBackgroundColor: 'var(--vf-color-blue)',
    triggerTextColor: '#fff',
    triggerShadow: '0 10px 24px rgba(0, 0, 0, 0.16)',
    actionSize: '2.5rem',
    actionPaddingX: '0.7rem',
    actionBorderRadius: '999px',
    actionBorderColor: 'var(--vf-border-color)',
    actionBackgroundColor: 'var(--vf-bg-color)',
    actionTextColor: 'var(--vf-text-color)',
    actionShadow: '0 8px 20px rgba(0, 0, 0, 0.14)',
    labelBackgroundColor: 'transparent',
    labelTextColor: 'inherit',
    labelPadding: '0',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    focusBorderColor: 'var(--vf-color-blue)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
