export default {
    minHeight: '100vh',
    gap: '0',
    padding: '1rem',
    panelPadding: '0.75rem',
    controlsGap: '0.5rem',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    primaryBackgroundColor: 'var(--vf-bg-color)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    toggleSize: '2rem',
    toggleBorderRadius: 'var(--vf-radii-md)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-text-color)',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.34)',
    zIndex: '110',
};
