export default {
    gap: '0.75rem',
    listGap: '0.5rem',
    listBorderWidth: '2px',
    listBorderColor: 'var(--vf-border-color)',
    listVerticalPadding: '0.75rem',
    tabPadding: '0.45rem 0.75rem',
    tabFontSize: 'var(--vf-typography-font-size)',
    tabFontWeight: '400',
    tabBorderRadius: '0',
    tabTextColor: 'var(--vf-secondary-text-color)',
    tabBackgroundColor: 'transparent',
    tabHoverBackgroundColor: 'transparent',
    tabActiveTextColor: 'var(--vf-text-color)',
    tabActiveBackgroundColor: 'transparent',
    tabActiveBorderColor: 'var(--vf-blue)',
    tabActiveBorderWidth: '2px',
    tabActiveFontWeight: '600',
    panelPadding: '0',
    panelBorderRadius: 'var(--vf-radii-md)',
    panelBackgroundColor: 'transparent',
    panelTextColor: 'var(--vf-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
