export default {
    minWidth: '12rem',
    minHeight: 'var(--vf-controls-height)',
    fontSize: 'var(--vf-typography-font-size)',
    controlGap: '0.5rem',
    chevronSize: '0.9em',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    panelPadding: '0.35rem',
    panelMaxHeight: '16rem',
    panelRadiusOffset: '2px',
    panelShadow: '0 10px 30px rgba(0, 0, 0, 0.12)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    optionPadding: '0.5rem 0.6rem',
    optionBorderRadius: 'var(--vf-radii-md)',
    optionHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    optionHighlightedBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    emptyPadding: '0.5rem 0.6rem',
    emptyColor: 'var(--vf-secondary-text-color)',
    loadingPadding: '0.5rem 0.6rem',
    loadingColor: 'var(--vf-secondary-text-color)',
    inputMinWidth: '4rem',
    chipGap: '0.35rem',
    chipPadding: '0.2rem 0.45rem',
    chipRadius: 'var(--vf-radii-sm)',
    chipBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.12)',
    chipTextColor: 'var(--vf-text-color)',
    chipFontSize: '0.875em',
    chipRemoveSize: '1rem',
    chipRemoveRadius: 'var(--vf-radii-sm)',
    chipRemoveHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    clearSize: '1.25rem',
    clearRadius: 'var(--vf-radii-sm)',
    clearHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        chipPadding: '0.15rem 0.35rem',
        chipFontSize: '0.8em',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        chipPadding: '0.25rem 0.55rem',
        chipFontSize: '0.9em',
    },
};
