export default {
    zIndex: '120',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.45)',
    width: '22rem',
    maxWidth: 'min(92vw, 24rem)',
    padding: '0.875rem',
    borderRadius: 'var(--vf-radii-lg)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    shadow: '0 14px 36px rgba(0, 0, 0, 0.22)',
    titleGap: '0.35rem',
    titleFontSize: '1rem',
    titleLineHeight: '1.35',
    titleFontWeight: '600',
    contentGap: '0.55rem',
    contentFontSize: '0.9375rem',
    contentLineHeight: '1.45',
    contentColor: 'var(--vf-secondary-text-color)',
    progressGap: '0.6rem',
    progressFontSize: '0.8125rem',
    progressColor: 'var(--vf-secondary-text-color)',
    actionsGap: '0.5rem',
    buttonMinWidth: '4.5rem',
    buttonPadding: '0.4rem 0.7rem',
    buttonRadius: 'var(--vf-radii-md)',
    buttonBorderColor: 'var(--vf-blue-600)',
    buttonBackgroundColor: 'var(--vf-blue-600)',
    buttonTextColor: 'var(--vf-white)',
    buttonHoverBackgroundColor: 'var(--vf-blue-700)',
    secondaryButtonBorderColor: 'var(--vf-border-color)',
    secondaryButtonBackgroundColor: 'transparent',
    secondaryButtonTextColor: 'var(--vf-text-color)',
    secondaryButtonHoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.12)',
    spotlightRadius: '10px',
    spotlightBorderWidth: '2px',
    spotlightBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.55)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
