export default {
    gap: '0.3rem',
    indent: '1rem',
    rowGap: '0.5rem',
    rowPadding: '0.45rem 0.65rem',
    rowPaddingInline: '0.65rem',
    rowBorderRadius: 'var(--vf-radii-md)',
    rowBorderColor: 'var(--vf-border-color)',
    rowFontSize: 'var(--vf-typography-font-size)',
    rowTextColor: 'var(--vf-text-color)',
    rowBackgroundColor: 'transparent',
    rowHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    rowSelectedBackgroundColor: 'rgba(var(--vf-blue-rgb), 0.12)',
    rowSelectedTextColor: 'var(--vf-text-color)',
    toggleSize: '1rem',
    toggleRadius: 'var(--vf-radii-sm)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-secondary-text-color)',
    toggleHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        rowPadding: '0.35rem 0.5rem',
        rowPaddingInline: '0.5rem',
        rowFontSize: '0.875rem',
        toggleSize: '0.875rem',
    },
    large: {
        rowPadding: '0.6rem 0.8rem',
        rowPaddingInline: '0.8rem',
        rowFontSize: '1rem',
        toggleSize: '1.1rem',
    },
};
