export default {
    minWidth: '14rem',
    fontSize: 'var(--vf-typography-font-size)',
    controlGap: '0.75rem',
    chevronSize: '0.9em',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    panelPadding: '0.35rem',
    panelMaxHeight: '18rem',
    panelRadiusOffset: '2px',
    panelShadow: '0 10px 30px rgba(0, 0, 0, 0.12)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    searchPadding: '0.25rem',
    searchBorderColor: 'var(--vf-border-color)',
    searchBorderRadius: 'var(--vf-radii-md)',
    emptyPadding: '0.6rem',
    emptyColor: 'var(--vf-secondary-text-color)',
    loadingPadding: '0.6rem',
    loadingColor: 'var(--vf-secondary-text-color)',
    clearSize: '1rem',
    clearRadius: '999px',
    clearHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
    },
};
