export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-lg)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    fontSize: 'var(--vf-typography-font-size)',
    headerBackgroundColor: 'var(--vf-bg-soft-color)',
    headerTextColor: 'var(--vf-text-color)',
    headerFontWeight: '600',
    headerBorderColor: 'var(--vf-border-color)',
    rowBackgroundColor: 'var(--vf-bg-color)',
    rowBorderColor: 'var(--vf-border-color)',
    rowHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    rowSelectedBackgroundColor: 'rgba(var(--vf-blue-rgb), 0.12)',
    rowSelectedTextColor: 'var(--vf-text-color)',
    rowStripedBackgroundColor: 'rgba(var(--vf-bg-soft-rgb), 0.4)',
    cellPadding: '0.65rem 0.75rem',
    cellGap: '0.35rem',
    indentStep: '1rem',
    toggleSize: '1rem',
    toggleBorderRadius: 'var(--vf-radii-sm)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-secondary-text-color)',
    focusRingColor: 'var(--vf-color-blue)',
    statePadding: '0.9rem',
    stateTextColor: 'var(--vf-secondary-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        fontSize: '0.875rem',
        cellPadding: '0.45rem 0.6rem',
    },
    large: {
        fontSize: '1rem',
        cellPadding: '0.75rem 0.9rem',
    },
};
