export const vfPrimitiveColorTokenNames = [
  'paletteNeutral0',
  'paletteNeutral50',
  'paletteNeutral100',
  'paletteNeutral200',
  'paletteNeutral250',
  'paletteNeutral300',
  'paletteNeutral400',
  'paletteNeutral500',
  'paletteNeutral600',
  'paletteNeutral700',
  'paletteNeutral750',
  'paletteNeutral800',
  'paletteNeutral850',
  'paletteNeutral900',
  'paletteNeutral950',
  'paletteNeutral1000',
  'palettePrimary500',
  'palettePrimary600',
  'paletteSuccess500',
  'paletteSuccess600',
  'paletteInfo500',
  'paletteInfo600',
  'paletteWarning400',
  'paletteWarning500',
  'paletteWarning950',
  'paletteDanger500',
  'paletteDanger600',
  'paletteHelp500',
  'paletteHelp600',
] as const;

export type VfPrimitiveColorTokenName = (typeof vfPrimitiveColorTokenNames)[number];
export type VfPrimitiveColorTokens = Partial<Record<VfPrimitiveColorTokenName, string>>;

export const vfSemanticColorTokenNames = [
  'colorBackgroundCanvas',
  'colorBackgroundSurface',
  'colorBackgroundSurfaceSubtle',
  'colorBackgroundSurfaceElevated',
  'colorBackgroundSurfaceHover',
  'colorBackgroundSurfaceActive',
  'colorBackgroundSurfaceSelected',
  'colorBackgroundSurfaceDisabled',
  'colorBackgroundInverse',
  'colorBackgroundInverseSubtle',
  'colorBackgroundBackdrop',
  'colorTextPrimary',
  'colorTextSecondary',
  'colorTextMuted',
  'colorTextDisabled',
  'colorTextPlaceholder',
  'colorTextInverse',
  'colorIconPrimary',
  'colorIconSecondary',
  'colorIconDisabled',
  'colorIconInverse',
  'colorBorderSubtle',
  'colorBorderDefault',
  'colorBorderStrong',
  'colorBorderInteractive',
  'colorBorderDisabled',
  'colorBorderFocus',
  'colorBorderDivider',
  'colorBorderInverse',
  'colorInteractivePrimaryBackground',
  'colorInteractivePrimaryHoverBackground',
  'colorInteractivePrimaryActiveBackground',
  'colorInteractivePrimarySubtleBackground',
  'colorInteractivePrimaryForeground',
  'colorInteractivePrimaryBorder',
  'colorFocusRing',
  'colorSelectedForeground',
  'colorStatusSuccessSolidBackground',
  'colorStatusSuccessSolidForeground',
  'colorStatusSuccessSubtleBackground',
  'colorStatusSuccessSubtleForeground',
  'colorStatusSuccessBorder',
  'colorStatusSuccessIcon',
  'colorStatusSuccessHoverBackground',
  'colorStatusSuccessActiveBackground',
  'colorStatusWarningSolidBackground',
  'colorStatusWarningSolidForeground',
  'colorStatusWarningSubtleBackground',
  'colorStatusWarningSubtleForeground',
  'colorStatusWarningBorder',
  'colorStatusWarningIcon',
  'colorStatusWarningHoverBackground',
  'colorStatusWarningActiveBackground',
  'colorStatusDangerSolidBackground',
  'colorStatusDangerSolidForeground',
  'colorStatusDangerSubtleBackground',
  'colorStatusDangerSubtleForeground',
  'colorStatusDangerBorder',
  'colorStatusDangerIcon',
  'colorStatusDangerHoverBackground',
  'colorStatusDangerActiveBackground',
  'colorStatusInfoSolidBackground',
  'colorStatusInfoSolidForeground',
  'colorStatusInfoSubtleBackground',
  'colorStatusInfoSubtleForeground',
  'colorStatusInfoBorder',
  'colorStatusInfoIcon',
  'colorStatusInfoHoverBackground',
  'colorStatusInfoActiveBackground',
  'colorStatusHelpSolidBackground',
  'colorStatusHelpSolidForeground',
  'colorStatusHelpSubtleBackground',
  'colorStatusHelpSubtleForeground',
  'colorStatusHelpBorder',
  'colorStatusHelpIcon',
  'colorStatusHelpHoverBackground',
  'colorStatusHelpActiveBackground',
] as const;

export type VfSemanticColorTokenName = (typeof vfSemanticColorTokenNames)[number];
export type VfSemanticColorTokens = Partial<Record<VfSemanticColorTokenName, string>>;
