export default {
    zIndex: '110',
    maxWidth: '40rem',
    maxHeight: '85vh',
    minHeightSm: '12rem',
    minHeight: '18rem',
    minHeightLg: '28rem',
    borderRadius: '1rem',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.42)',
    shadow: '0 -14px 30px rgba(0, 0, 0, 0.22)',
    safeAreaBottom: '0rem',
    handleWidth: '2.8rem',
    handleHeight: '0.32rem',
    handleColor: 'rgba(var(--vf-gray-600-rgb), 0.38)',
    handleMargin: '0.6rem auto 0.3rem',
    headerGap: '0.5rem',
    headerPadding: '0.25rem 1rem 0.35rem',
    titleFontSize: '1rem',
    titleLineHeight: '1.3',
    titleFontWeight: '600',
    closeSize: '1.9rem',
    closeRadius: '999px',
    closeColor: 'var(--vf-text-color)',
    closeFontSize: '1.2rem',
    closeHoverBackgroundColor: 'rgba(var(--vf-gray-700-rgb), 0.12)',
    bodyPadding: '0.25rem 1rem 1rem',
    footerPadding: '0.35rem 1rem 1rem',
    footerGap: '0.45rem',
};
