export default {
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    roundedBorderRadius: '2rem',
    iconGap: '6px',
    small: {
        fontSize: 'var(--vf-sizes-sm-font-size)',
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
    },
    large: {
        fontSize: 'var(--vf-sizes-lg-font-size)',
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
    },
    colorScheme: {
        light: {
            primary: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--vf-blue)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--vf-blue)',
                hoverBorderColor: 'var(--vf-blue-600)',
                activeBorderColor: 'var(--vf-blue-700)',
                hoverBackgroundColor: 'var(--vf-blue-600)',
                activeBackgroundColor: 'var(--vf-blue-700)',
            },
            secondary: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--vf-gray)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--vf-gray)',
                hoverBorderColor: 'var(--vf-gray-600)',
                activeBorderColor: 'var(--vf-gray-700)',
                hoverBackgroundColor: 'var(--vf-gray-600)',
                activeBackgroundColor: 'var(--vf-gray-700)',
            },
            success: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--vf-green)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--vf-green)',
                hoverBorderColor: 'var(--vf-green-600)',
                activeBorderColor: 'var(--vf-green-700)',
                hoverBackgroundColor: 'var(--vf-green-600)',
                activeBackgroundColor: 'var(--vf-green-700)',
            },
            danger: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--vf-red)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--vf-red)',
                hoverBorderColor: 'var(--vf-red-600)',
                activeBorderColor: 'var(--vf-red-700)',
                hoverBackgroundColor: 'var(--vf-red-600)',
                activeBackgroundColor: 'var(--vf-red-700)',
            },
            warning: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--vf-yellow)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--vf-yellow)',
                hoverBorderColor: 'var(--vf-yellow-600)',
                activeBorderColor: 'var(--vf-yellow-700)',
                hoverBackgroundColor: 'var(--vf-yellow-600)',
                activeBackgroundColor: 'var(--vf-yellow-700)',
            },
            info: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--vf-sky)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--vf-sky)',
                hoverBorderColor: 'var(--vf-sky-600)',
                activeBorderColor: 'var(--vf-sky-700)',
                hoverBackgroundColor: 'var(--vf-sky-600)',
                activeBackgroundColor: 'var(--vf-sky-700)',
            },
            text: {
                primary: {
                    color: 'var(--vf-blue)',
                    hoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), .1)',
                },
                secondary: {
                    color: 'var(--vf-gray)',
                    hoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), .1)',
                },
                success: {
                    color: 'var(--vf-green)',
                    hoverBackgroundColor: 'rgba(var(--vf-green-600-rgb), .1)',
                },
                danger: {
                    color: 'var(--vf-red)',
                    hoverBackgroundColor: 'rgba(var(--vf-red-600-rgb), .1)',
                },
                warning: {
                    color: 'var(--vf-yellow)',
                    hoverBackgroundColor: 'rgba(var(--vf-yellow-600-rgb), .1)',
                },
                info: {
                    color: 'var(--vf-sky)',
                    hoverBackgroundColor: 'rgba(var(--vf-sky-600-rgb), .1)',
                },
            },
            outlined: {
                primary: {
                    color: 'var(--vf-blue)',
                    borderColor: 'rgba(var(--vf-blue-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), .1)',
                },
                secondary: {
                    color: 'var(--vf-gray)',
                    borderColor: 'rgba(var(--vf-gray-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), .1)',
                },
                success: {
                    color: 'var(--vf-green)',
                    borderColor: 'rgba(var(--vf-green-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--vf-green-600-rgb), .1)',
                },
                danger: {
                    color: 'var(--vf-red)',
                    borderColor: 'rgba(var(--vf-red-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--vf-red-600-rgb), .1)',
                },
                warning: {
                    color: 'var(--vf-yellow)',
                    borderColor: 'rgba(var(--vf-yellow-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--vf-yellow-600-rgb), .1)',
                },
                info: {
                    color: 'var(--vf-sky)',
                    borderColor: 'rgba(var(--vf-sky-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--vf-sky-600-rgb), .1)',
                },
            },
        },
    },
};
