export default {
    padding: '6px 10px',
    borderRadius: '6px',
    roundedBorderRadius: '2rem',
    small: {
        fontSize: '0.875rem',
        padding: '4px 8px',
    },
    large: {
        fontSize: '1.125rem',
        padding: '4px 8px',
    },
    colorScheme: {
        light: {
            primary: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--cm-blue)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--cm-blue)',
                hoverBorderColor: 'var(--cm-blue-600)',
                activeBorderColor: 'var(--cm-blue-700)',
                hoverBackgroundColor: 'var(--cm-blue-600)',
                activeBackgroundColor: 'var(--cm-blue-700)',
            },
            secondary: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--cm-gray)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--cm-gray)',
                hoverBorderColor: 'var(--cm-gray-600)',
                activeBorderColor: 'var(--cm-gray-700)',
                hoverBackgroundColor: 'var(--cm-gray-600)',
                activeBackgroundColor: 'var(--cm-gray-700)',
            },
            success: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--cm-green)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--cm-green)',
                hoverBorderColor: 'var(--cm-green-600)',
                activeBorderColor: 'var(--cm-green-700)',
                hoverBackgroundColor: 'var(--cm-green-600)',
                activeBackgroundColor: 'var(--cm-green-700)',
            },
            danger: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--cm-red)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--cm-red)',
                hoverBorderColor: 'var(--cm-red-600)',
                activeBorderColor: 'var(--cm-red-700)',
                hoverBackgroundColor: 'var(--cm-red-600)',
                activeBackgroundColor: 'var(--cm-red-700)',
            },
            warning: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--cm-yellow)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--cm-yellow)',
                hoverBorderColor: 'var(--cm-yellow-600)',
                activeBorderColor: 'var(--cm-yellow-700)',
                hoverBackgroundColor: 'var(--cm-yellow-600)',
                activeBackgroundColor: 'var(--cm-yellow-700)',
            },
            info: {
                color: '#FFFFFF',
                hoverColor: '#FFFFFF',
                borderColor: 'var(--cm-sky)',
                activeColor: '#FFFFFF',
                backgroundColor: 'var(--cm-sky)',
                hoverBorderColor: 'var(--cm-sky-600)',
                activeBorderColor: 'var(--cm-sky-700)',
                hoverBackgroundColor: 'var(--cm-sky-600)',
                activeBackgroundColor: 'var(--cm-sky-700)',
            },
            text: {
                primary: {
                    color: 'var(--cm-blue)',
                    hoverBackgroundColor: 'rgba(var(--cm-blue-600-rgb), .1)',
                },
                secondary: {
                    color: 'var(--cm-gray)',
                    hoverBackgroundColor: 'rgba(var(--cm-gray-600-rgb), .1)',
                },
                success: {
                    color: 'var(--cm-green)',
                    hoverBackgroundColor: 'rgba(var(--cm-green-600-rgb), .1)',
                },
                danger: {
                    color: 'var(--cm-red)',
                    hoverBackgroundColor: 'rgba(var(--cm-red-600-rgb), .1)',
                },
                warning: {
                    color: 'var(--cm-yellow)',
                    hoverBackgroundColor: 'rgba(var(--cm-yellow-600-rgb), .1)',
                },
                info: {
                    color: 'var(--cm-sky)',
                    hoverBackgroundColor: 'rgba(var(--cm-sky-600-rgb), .1)',
                },
            },
            outlined: {
                primary: {
                    color: 'var(--cm-blue)',
                    borderColor: 'rgba(var(--cm-blue-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--cm-blue-600-rgb), .1)',
                },
                secondary: {
                    color: 'var(--cm-gray)',
                    borderColor: 'rgba(var(--cm-gray-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--cm-gray-600-rgb), .1)',
                },
                success: {
                    color: 'var(--cm-green)',
                    borderColor: 'rgba(var(--cm-green-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--cm-green-600-rgb), .1)',
                },
                danger: {
                    color: 'var(--cm-red)',
                    borderColor: 'rgba(var(--cm-red-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--cm-red-600-rgb), .1)',
                },
                warning: {
                    color: 'var(--cm-yellow)',
                    borderColor: 'rgba(var(--cm-yellow-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--cm-yellow-600-rgb), .1)',
                },
                info: {
                    color: 'var(--cm-sky)',
                    borderColor: 'rgba(var(--cm-sky-rgb), .4)',
                    hoverBackgroundColor: 'rgba(var(--cm-sky-600-rgb), .1)',
                },
            },
        },
    },
};