export default {
    width: '100%',
    fontSize: 'var(--vf-typography-font-size)',
    padding: '0.5rem',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    headerGap: '0.5rem',
    headerPadding: '0 0 0.4rem',
    monthLabelFontSize: '0.95rem',
    monthLabelFontWeight: '600',
    navButtonSize: '1.8rem',
    navButtonRadius: 'var(--vf-radii-sm)',
    navButtonFontSize: '1.1rem',
    weekdayColor: 'var(--vf-secondary-text-color)',
    weekdayFontSize: '0.75rem',
    weekdaysMarginBottom: '0.35rem',
    daysGap: '0.15rem',
    daySize: '2rem',
    dayFontSize: '0.875rem',
    dayBorderRadius: 'var(--vf-radii-sm)',
    dayHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    daySelectedBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    daySelectedTextColor: 'var(--vf-text-color)',
    dayMutedColor: 'var(--vf-secondary-text-color)',
    dayTodayBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.45)',
    small: {
        padding: '0.375rem',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        daySize: '1.8rem',
    },
    large: {
        padding: '0.65rem',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        daySize: '2.2rem',
    },
};
