export default {
    fontSize: '0.8125rem',
    lineHeight: '1',
    paddingX: '0.55rem',
    paddingY: '0.2rem',
    borderRadius: '999px',
    gap: '0.35rem',
    backgroundColor: 'var(--vf-gutter-color)',
    textColor: 'var(--vf-secondary-text-color)',
    borderColor: 'var(--vf-gutter-color)',
    softBackgroundColor: 'rgba(var(--vf-gray-500-rgb), 0.16)',
    softTextColor: 'var(--vf-secondary-text-color)',
    softBorderColor: 'rgba(var(--vf-gray-500-rgb), 0.18)',
    outlineTextColor: 'var(--vf-secondary-text-color)',
    outlineBorderColor: 'rgba(var(--vf-gray-500-rgb), 0.35)',
    iconSize: '1em',
    closeSize: '1.15em',
    closeFontSize: '0.95em',
    closeRadius: '999px',
    closeColor: 'currentColor',
    closeHoverBackgroundColor: 'rgba(var(--vf-gray-500-rgb), 0.18)',
    disabledOpacity: '0.6',
    info: {
        backgroundColor: 'var(--vf-sky-600)',
        textColor: 'var(--vf-white)',
        borderColor: 'var(--vf-sky-600)',
        softBackgroundColor: 'rgba(var(--vf-sky-500-rgb), 0.18)',
        softTextColor: 'var(--vf-sky-700)',
        softBorderColor: 'rgba(var(--vf-sky-500-rgb), 0.3)',
        outlineTextColor: 'var(--vf-sky-600)',
        outlineBorderColor: 'rgba(var(--vf-sky-600-rgb), 0.45)',
    },
    success: {
        backgroundColor: 'var(--vf-green-600)',
        textColor: 'var(--vf-white)',
        borderColor: 'var(--vf-green-600)',
        softBackgroundColor: 'rgba(var(--vf-green-500-rgb), 0.2)',
        softTextColor: 'var(--vf-green-700)',
        softBorderColor: 'rgba(var(--vf-green-500-rgb), 0.32)',
        outlineTextColor: 'var(--vf-green-600)',
        outlineBorderColor: 'rgba(var(--vf-green-600-rgb), 0.45)',
    },
    warn: {
        backgroundColor: 'var(--vf-yellow-600)',
        textColor: 'rgba(0, 0, 0, 0.82)',
        borderColor: 'var(--vf-yellow-600)',
        softBackgroundColor: 'rgba(var(--vf-yellow-500-rgb), 0.22)',
        softTextColor: 'rgba(0, 0, 0, 0.78)',
        softBorderColor: 'rgba(var(--vf-yellow-500-rgb), 0.4)',
        outlineTextColor: 'var(--vf-yellow-700)',
        outlineBorderColor: 'rgba(var(--vf-yellow-600-rgb), 0.55)',
    },
    danger: {
        backgroundColor: 'var(--vf-red-600)',
        textColor: 'var(--vf-white)',
        borderColor: 'var(--vf-red-600)',
        softBackgroundColor: 'rgba(var(--vf-red-500-rgb), 0.2)',
        softTextColor: 'var(--vf-red-700)',
        softBorderColor: 'rgba(var(--vf-red-500-rgb), 0.32)',
        outlineTextColor: 'var(--vf-red-600)',
        outlineBorderColor: 'rgba(var(--vf-red-600-rgb), 0.45)',
    },
    small: {
        fontSize: '0.75rem',
        paddingX: '0.45rem',
        paddingY: '0.15rem',
    },
    large: {
        fontSize: '0.95rem',
        paddingX: '0.7rem',
        paddingY: '0.28rem',
    },
};
