export default {
    gap: '0',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: '#0f172a',
    textColor: '#e2e8f0',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.8125rem',
    lineHeight: '1.5',
    padding: '0.75rem 0.9rem',
    headerGap: '0.75rem',
    headerPadding: '0.55rem 0.75rem',
    headerBorderColor: 'rgba(148, 163, 184, 0.35)',
    metaGap: '0.55rem',
    metaColor: '#93a4bf',
    metaFontSize: '0.75rem',
    filenameColor: '#e2e8f0',
    filenameFontWeight: '600',
    actionsGap: '0.45rem',
    actionBorderColor: 'rgba(148, 163, 184, 0.45)',
    actionBorderRadius: 'var(--vf-radii-sm)',
    actionBackgroundColor: 'rgba(15, 23, 42, 0.7)',
    actionTextColor: '#e2e8f0',
    actionPadding: '0.2rem 0.55rem',
    actionFontSize: '0.75rem',
    lineGap: '0.7rem',
    lineNumberColor: '#64748b',
    lineNumberMinWidth: '2.1rem',
    tokenKeywordColor: '#c084fc',
    tokenStringColor: '#86efac',
    tokenNumberColor: '#fca5a5',
    tokenCommentColor: '#94a3b8',
    tokenVariableColor: '#67e8f9',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
