export default {
    minWidth: '12rem',
    gap: '0.5rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    swatchSize: '1rem',
    swatchRadius: 'var(--vf-radii-sm)',
    panelPadding: '0.6rem',
    panelBorderColor: 'var(--vf-border-color)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelShadow: '0 10px 30px rgba(0, 0, 0, 0.12)',
    panelGap: '0.5rem',
    rangeAccentColor: 'var(--vf-blue-600)',
    presetSize: '1.3rem',
    presetRadius: 'var(--vf-radii-sm)',
    presetBorderColor: 'var(--vf-border-color)',
    presetHoverBorderColor: 'var(--vf-blue-500)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        swatchSize: '0.85rem',
        presetSize: '1.1rem',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        swatchSize: '1.15rem',
        presetSize: '1.5rem',
    },
};
