export default {
    width: '92vw',
    maxWidth: '640px',
    maxHeight: '70vh',
    padding: '0.75rem',
    borderRadius: '12px',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.4)',
    shadow: '0 24px 60px rgba(0, 0, 0, 0.24)',
    zIndex: '110',
    headerGap: '0.5rem',
    inputPadding: '0.625rem 0.75rem',
    inputBorderRadius: '8px',
    inputBorderColor: 'var(--vf-border-color)',
    inputBackgroundColor: 'var(--vf-bg-soft-color)',
    inputTextColor: 'var(--vf-text-color)',
    inputPlaceholderColor: 'var(--vf-secondary-text-color)',
    inputFocusBorderColor: 'var(--vf-blue-600)',
    inputFocusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    listGap: '0.5rem',
    groupGap: '0.25rem',
    groupLabelPadding: '0.25rem 0.5rem',
    groupLabelColor: 'var(--vf-secondary-text-color)',
    groupLabelFontSize: '0.7rem',
    itemPadding: '0.5rem 0.625rem',
    itemBorderRadius: '8px',
    itemGap: '0.2rem',
    itemTextColor: 'var(--vf-text-color)',
    itemDescriptionColor: 'var(--vf-secondary-text-color)',
    itemDescriptionFontSize: '0.8125rem',
    itemActiveBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    itemActiveTextColor: 'var(--vf-text-color)',
    itemDisabledOpacity: 'var(--vf-states-disabled-opacity)',
    shortcutPadding: '0.2rem 0.35rem',
    shortcutBorderRadius: '6px',
    shortcutBorderColor: 'var(--vf-border-color)',
    shortcutBackgroundColor: 'var(--vf-bg-soft-color)',
    shortcutTextColor: 'var(--vf-secondary-text-color)',
    shortcutFontSize: '0.75rem',
    emptyPadding: '1rem 0.5rem',
    emptyColor: 'var(--vf-secondary-text-color)',
};
