export default {
    gap: '0.75rem',
    toolbarGap: '0.5rem',
    layoutGap: '0.4rem',
    controlBorderColor: 'var(--vf-border-color)',
    controlBorderRadius: 'var(--vf-radii-md)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlPadding: '0.4rem 0.65rem',
    controlFontSize: '0.875rem',
    controlActiveBackgroundColor: 'rgba(var(--vf-blue-rgb), 0.12)',
    controlActiveBorderColor: 'var(--vf-color-blue)',
    controlActiveTextColor: 'var(--vf-text-color)',
    listGap: '0.5rem',
    gridGap: '0.75rem',
    gridMinWidth: '14rem',
    itemBorderColor: 'var(--vf-border-color)',
    itemBorderRadius: 'var(--vf-radii-md)',
    itemBackgroundColor: 'var(--vf-bg-color)',
    itemTextColor: 'var(--vf-text-color)',
    itemPadding: '0.65rem',
    statePadding: '0.9rem',
    stateTextColor: 'var(--vf-secondary-text-color)',
    paginationGap: '0.5rem',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
