export default {
    minWidth: '12rem',
    fontSize: 'var(--vf-typography-font-size)',
    controlGap: '0.75rem',
    chevronSize: '0.9em',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    panelWidth: '17rem',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    panelPadding: '0.5rem',
    panelRadiusOffset: '2px',
    panelShadow: '0 10px 30px rgba(0, 0, 0, 0.12)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    headerGap: '0.5rem',
    headerPadding: '0 0 0.4rem',
    monthLabelFontSize: '0.95rem',
    monthLabelFontWeight: '600',
    navButtonSize: '1.8rem',
    navButtonRadius: 'var(--vf-radii-sm)',
    navButtonFontSize: '1.1rem',
    weekdayColor: 'var(--vf-secondary-text-color)',
    weekdayFontSize: '0.75rem',
    weekdaysMarginBottom: '0.35rem',
    daysGap: '0.15rem',
    daySize: '2rem',
    dayFontSize: '0.875rem',
    dayBorderRadius: 'var(--vf-radii-sm)',
    dayHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    daySelectedBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    daySelectedTextColor: 'var(--vf-text-color)',
    dayMutedColor: 'var(--vf-secondary-text-color)',
    dayTodayBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.45)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        daySize: '1.8rem',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        daySize: '2.2rem',
    },
};
