export default {
    gap: '0.65rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.7rem',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.8125rem',
    lineHeight: '1.35',
    toolbarGap: '0.5rem',
    toolbarGroupGap: '0.4rem',
    controlBorderColor: 'var(--vf-border-color)',
    controlBorderRadius: 'var(--vf-radii-sm)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlFontSize: '0.75rem',
    controlPadding: '0.2rem 0.45rem',
    controlActiveBackgroundColor: 'rgba(var(--vf-primary-color-rgb), 0.14)',
    controlActiveBorderColor: 'var(--vf-primary-color)',
    controlActiveTextColor: 'var(--vf-text-color)',
    dividerColor: 'var(--vf-border-color)',
    cellPadding: '0.4rem',
    rowGap: '0.3rem',
    cellGap: '0.4rem',
    rowBorderRadius: 'var(--vf-radii-sm)',
    lineColor: 'var(--vf-secondary-text-color)',
    markerColor: 'var(--vf-secondary-text-color)',
    addedBackgroundColor: 'rgba(var(--vf-green-600-rgb), 0.1)',
    removedBackgroundColor: 'rgba(var(--vf-red-600-rgb), 0.1)',
    changedBackgroundColor: 'rgba(var(--vf-yellow-600-rgb), 0.14)',
    emptyColor: 'var(--vf-secondary-text-color)',
};
