export default {
    gap: '0.75rem',
    bodyGap: '0.35rem',
    padding: '1.25rem',
    borderRadius: 'var(--vf-radii-lg)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    maxWidth: '36rem',
    iconSize: '2rem',
    iconColor: 'var(--vf-secondary-text-color)',
    titleFontSize: '1rem',
    titleLineHeight: '1.35',
    titleFontWeight: '600',
    titleColor: 'var(--vf-text-color)',
    descriptionFontSize: '0.9375rem',
    descriptionLineHeight: '1.45',
    descriptionColor: 'var(--vf-secondary-text-color)',
    actionsGap: '0.5rem',
    small: {
        padding: '0.9rem',
        iconSize: '1.5rem',
        titleFontSize: '0.9375rem',
        descriptionFontSize: '0.875rem',
    },
    large: {
        padding: '1.5rem',
        iconSize: '2.4rem',
        titleFontSize: '1.125rem',
        descriptionFontSize: '1rem',
    },
};
