export default {
    gap: '0.75rem',
    toolbarGap: '0.75rem',
    toolbarControlsGap: '0.5rem',
    viewGap: '0.4rem',
    controlBorderColor: 'var(--vf-border-color)',
    controlBorderRadius: 'var(--vf-radii-sm)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlFontSize: '0.8125rem',
    controlPadding: '0.35rem 0.6rem',
    controlActiveBackgroundColor: 'rgba(var(--vf-primary-color-rgb), 0.14)',
    controlActiveBorderColor: 'var(--vf-primary-color)',
    controlActiveTextColor: 'var(--vf-text-color)',
    listGap: '0.55rem',
    gridGap: '0.75rem',
    gridMinWidth: '12.5rem',
    itemGap: '0.55rem',
    itemPadding: '0.6rem',
    itemBorderColor: 'var(--vf-border-color)',
    itemBorderRadius: 'var(--vf-radii-md)',
    itemBackgroundColor: 'var(--vf-bg-color)',
    itemTextColor: 'var(--vf-text-color)',
    itemSelectedBorderColor: 'var(--vf-primary-color)',
    itemSelectedBackgroundColor: 'rgba(var(--vf-primary-color-rgb), 0.08)',
    thumbSize: '2.25rem',
    thumbRadius: 'var(--vf-radii-sm)',
    thumbBorderColor: 'var(--vf-border-color)',
    thumbBackgroundColor: 'var(--vf-gutter-color)',
    thumbFontSize: '0.6875rem',
    thumbTextColor: 'var(--vf-secondary-text-color)',
    nameFontSize: '0.875rem',
    nameFontWeight: '600',
    detailsGap: '0.45rem',
    detailsFontSize: '0.75rem',
    detailsColor: 'var(--vf-secondary-text-color)',
    statePadding: '1rem',
    stateBorderColor: 'var(--vf-border-color)',
    stateBorderRadius: 'var(--vf-radii-md)',
    stateColor: 'var(--vf-secondary-text-color)',
    previewZIndex: '1200',
    previewPadding: '1rem',
    previewOverlayBackgroundColor: 'rgba(0, 0, 0, 0.56)',
    previewMaxWidth: '48rem',
    previewMaxHeight: '70vh',
    previewGap: '0.65rem',
    previewBorderColor: 'var(--vf-border-color)',
    previewBorderRadius: 'var(--vf-radii-md)',
    previewBackgroundColor: 'var(--vf-bg-color)',
    previewTextColor: 'var(--vf-text-color)',
    previewDialogPadding: '0.75rem',
    previewImageRadius: 'var(--vf-radii-sm)',
    disabledOpacity: '0.6',
};
