export default {
    fontSize: '0.8125rem',
    gap: '0.35rem',
    chipGap: '0.3rem',
    chipPadding: '0.3rem 0.55rem',
    chipBorderRadius: '999px',
    chipBorderColor: 'rgba(var(--vf-gray-500-rgb), 0.24)',
    chipBackgroundColor: 'rgba(var(--vf-gray-500-rgb), 0.14)',
    chipTextColor: 'var(--vf-secondary-text-color)',
    chipHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    chipHoverBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.35)',
    chipActiveBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.16)',
    chipActiveBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.5)',
    chipActiveTextColor: 'var(--vf-blue-700)',
    chipSolidActiveBackgroundColor: 'var(--vf-blue-600)',
    chipSolidActiveBorderColor: 'var(--vf-blue-600)',
    chipSolidActiveTextColor: 'var(--vf-white)',
    countPadding: '0.1rem 0.35rem',
    countFontSize: '0.72em',
    countBackgroundColor: 'rgba(var(--vf-gray-500-rgb), 0.2)',
    countTextColor: 'var(--vf-secondary-text-color)',
    countActiveBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.2)',
    countActiveTextColor: 'var(--vf-blue-700)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        fontSize: '0.75rem',
        chipPadding: '0.24rem 0.46rem',
    },
    large: {
        fontSize: '0.95rem',
        chipPadding: '0.38rem 0.72rem',
    },
};
