export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-soft-color)',
    overlayZIndex: '1600',
    overlayPadding: '1rem',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.7)',
    previewMaxWidth: '72rem',
    previewMaxHeight: '52rem',
    previewBorderRadius: 'var(--vf-radii-lg)',
    previewBackgroundColor: 'rgba(17, 24, 39, 0.92)',
    previewShadow: '0 20px 40px rgba(0, 0, 0, 0.45)',
    closeOffset: '0.5rem',
    closeSize: '2rem',
    closeBorderColor: 'rgba(255, 255, 255, 0.35)',
    closeBackgroundColor: 'rgba(17, 24, 39, 0.75)',
    closeTextColor: '#fff',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
