export default {
    gap: '0.65rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.7rem',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.8125rem',
    lineHeight: '1.35',
    indentSize: '1rem',
    toolbarGap: '0.5rem',
    toolbarGroupGap: '0.4rem',
    controlBorderColor: 'var(--vf-border-color)',
    controlBorderRadius: 'var(--vf-radii-sm)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlFontSize: '0.75rem',
    controlPadding: '0.2rem 0.45rem',
    toggleSize: '1.1rem',
    rowGap: '0.25rem',
    rowMinHeight: '1.25rem',
    cellGap: '0.35rem',
    keyColor: 'var(--vf-sky-700)',
    punctuationColor: 'var(--vf-secondary-text-color)',
    metaColor: 'var(--vf-secondary-text-color)',
    stringColor: 'var(--vf-green-700)',
    numberColor: 'var(--vf-blue-700)',
    booleanColor: 'var(--vf-purple-700)',
    nullColor: 'var(--vf-red-700)',
    emptyColor: 'var(--vf-secondary-text-color)',
};
