export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    padding: '0.875rem',
    gap: '0.65rem',
    headerGap: '0.75rem',
    titleFontSize: '0.875rem',
    titleFontWeight: '600',
    subtitleFontSize: '0.75rem',
    subtitleColor: 'var(--vf-secondary-text-color)',
    valueGap: '0.35rem',
    valueFontSize: '1.75rem',
    valueFontWeight: '700',
    trendGap: '0.3rem',
    trendFontSize: '0.8125rem',
    trendColor: 'var(--vf-secondary-text-color)',
    upColor: 'var(--vf-green-700)',
    downColor: 'var(--vf-red-700)',
    captionFontSize: '0.75rem',
    captionColor: 'var(--vf-secondary-text-color)',
};
