export default {
    minWidth: '14rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    panelPadding: '0.35rem',
    panelMaxHeight: '16rem',
    panelRadiusOffset: '2px',
    panelShadow: '0 10px 30px rgba(0, 0, 0, 0.12)',
    optionPadding: '0.45rem 0.55rem',
    optionGap: '0.35rem',
    optionBorderRadius: 'var(--vf-radii-sm)',
    optionFontSize: 'var(--vf-typography-font-size)',
    optionHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    optionTriggerColor: 'var(--vf-blue-600)',
    emptyPadding: '0.45rem 0.55rem',
    emptyColor: 'var(--vf-secondary-text-color)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
    },
};
