export default {
    gap: '0.75rem',
    itemGap: '0.6rem',
    itemBorderColor: 'var(--vf-border-color)',
    itemBorderRadius: 'var(--vf-radii-md)',
    itemBackgroundColor: 'var(--vf-bg-color)',
    itemPadding: '0.75rem',
    headerGap: '0.5rem',
    labelFontSize: '0.875rem',
    labelFontWeight: '600',
    valueFontSize: '0.8125rem',
    valueColor: 'var(--vf-secondary-text-color)',
    trackHeight: '0.5rem',
    trackBorderRadius: '999px',
    trackBackgroundColor: 'var(--vf-gray-200)',
    barColor: 'var(--vf-primary-color)',
    warnBarColor: 'var(--vf-yellow-600)',
    dangerBarColor: 'var(--vf-red-600)',
    descriptionFontSize: '0.75rem',
    descriptionColor: 'var(--vf-secondary-text-color)',
};
