export default {
    width: '90vw',
    maxWidth: '520px',
    maxHeight: '80vh',
    widthSm: '90vw',
    maxWidthSm: '420px',
    widthLg: '90vw',
    maxWidthLg: '720px',
    padding: '1.25rem',
    borderRadius: 'var(--vf-radii-lg)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    overlayBackgroundColor: 'rgba(0, 0, 0, 0.45)',
    shadow: '0 12px 40px rgba(0, 0, 0, 0.2)',
    zIndex: '100',
    headerGap: '0.75rem',
    bodyGap: '1rem',
    footerGap: '0.5rem',
    titleFontSize: '1.125rem',
    titleLineHeight: '1.4',
    titleFontWeight: '600',
    closeSize: '2rem',
    closeRadius: '999px',
    closeOffset: '0.5rem',
    closeColor: 'var(--vf-text-color)',
    closeFontSize: '1.25rem',
    closeHoverBackgroundColor: 'rgba(0, 0, 0, 0.06)',
};
