export default {
    gap: '0.5rem',
    fontSize: 'var(--vf-typography-font-size)',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-controls-background-color)',
    textColor: 'var(--vf-text-color)',
    placeholderColor: 'var(--vf-secondary-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    controlWidth: '1.5rem',
    controlGap: '0.1rem',
    controlFontSize: '0.7rem',
    controlRadius: 'var(--vf-radii-sm)',
    controlBackgroundColor: 'transparent',
    controlHoverBackgroundColor: 'var(--vf-gutter-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlBorderColor: 'var(--vf-border-color)',
    small: {
        padding: 'var(--vf-sizes-sm-padding-y) var(--vf-sizes-sm-padding-x)',
        fontSize: 'var(--vf-sizes-sm-font-size)',
        controlWidth: '1.25rem',
        controlFontSize: '0.6rem',
    },
    large: {
        padding: 'var(--vf-sizes-lg-padding-y) var(--vf-sizes-lg-padding-x)',
        fontSize: 'var(--vf-sizes-lg-font-size)',
        controlWidth: '1.75rem',
        controlFontSize: '0.8rem',
    },
};
