export default {
    gap: '1rem',
    childrenMarginTop: '1rem',
    connectorColor: 'var(--vf-border-color)',
    textColor: 'var(--vf-text-color)',
    cardMinWidth: '10rem',
    cardMaxWidth: '16rem',
    cardGap: '0.5rem',
    cardPadding: '0.55rem 0.65rem',
    cardBorderColor: 'var(--vf-border-color)',
    cardBorderRadius: 'var(--vf-radii-md)',
    cardBackgroundColor: 'var(--vf-bg-color)',
    cardTextColor: 'var(--vf-text-color)',
    cardHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    cardSelectedBackgroundColor: 'rgba(var(--vf-blue-rgb), 0.12)',
    cardSelectedColor: 'var(--vf-text-color)',
    toggleSize: '1rem',
    toggleRadius: 'var(--vf-radii-sm)',
    toggleBorderColor: 'var(--vf-border-color)',
    toggleBackgroundColor: 'var(--vf-bg-color)',
    toggleTextColor: 'var(--vf-secondary-text-color)',
    focusRingColor: 'var(--vf-color-blue)',
    labelFontSize: '0.95rem',
    labelFontWeight: '600',
    titleFontSize: '0.8rem',
    titleColor: 'var(--vf-secondary-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        cardPadding: '0.4rem 0.5rem',
        labelFontSize: '0.85rem',
    },
    large: {
        cardPadding: '0.7rem 0.8rem',
        labelFontSize: '1rem',
    },
};
