export default {
    minSize: '1.125rem',
    dotSize: '0.625rem',
    paddingX: '0.3rem',
    borderRadius: '999px',
    borderColor: 'var(--vf-red-600)',
    backgroundColor: 'var(--vf-red-600)',
    textColor: 'var(--vf-white)',
    fontSize: '0.6875rem',
    fontWeight: '700',
    lineHeight: '1',
    zIndex: '2',
    topOffset: '0',
    rightOffset: '0',
    bottomOffset: '0',
    leftOffset: '0',
    neutralBackgroundColor: 'var(--vf-gray-700)',
    neutralTextColor: 'var(--vf-white)',
    neutralBorderColor: 'var(--vf-gray-700)',
    infoBackgroundColor: 'var(--vf-sky-600)',
    infoTextColor: 'var(--vf-white)',
    infoBorderColor: 'var(--vf-sky-600)',
    successBackgroundColor: 'var(--vf-green-600)',
    successTextColor: 'var(--vf-white)',
    successBorderColor: 'var(--vf-green-600)',
    warnBackgroundColor: 'var(--vf-yellow-600)',
    warnTextColor: 'rgba(0, 0, 0, 0.82)',
    warnBorderColor: 'var(--vf-yellow-600)',
    dangerBackgroundColor: 'var(--vf-red-600)',
    dangerTextColor: 'var(--vf-white)',
    dangerBorderColor: 'var(--vf-red-600)',
};
