export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    padding: '0.45rem',
    gap: '0.25rem',
    indent: '0.85rem',
    groupPadding: '0 0 0 0.85rem',
    itemTextColor: 'var(--vf-text-color)',
    itemFontSize: '0.9rem',
    itemFontWeight: '400',
    itemBorderRadius: 'var(--vf-radii-sm)',
    itemPadding: '0.45rem 0.6rem',
    itemHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    itemActiveTextColor: 'var(--vf-link-active-color)',
    itemActiveBackgroundColor: 'var(--vf-bg-soft-color)',
    itemActiveFontWeight: '400',
    triggerActiveTextColor: 'var(--vf-text-color)',
    triggerActiveBackgroundColor: 'transparent',
    triggerActiveFontWeight: '600',
    linkActiveTextColor: 'var(--vf-link-active-color)',
    linkActiveBackgroundColor: 'var(--vf-bg-soft-color)',
    linkActiveFontWeight: '400',
    chevronSize: '1.25rem',
};
