export default {
    fontSize: '0.875rem',
    padding: '0.85rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-md)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    secondaryTextColor: 'var(--vf-secondary-text-color)',
    rowGap: '0.55rem',
    nestedOffset: '0.7rem',
    groupGap: '0.55rem',
    groupPadding: '0.7rem',
    groupBorderRadius: 'var(--vf-radii-md)',
    groupBorderColor: 'rgba(var(--vf-gray-500-rgb), 0.24)',
    groupBackgroundColor: 'rgba(var(--vf-gray-500-rgb), 0.06)',
    controlHeight: '2rem',
    controlBorderRadius: 'var(--vf-radii-sm)',
    controlBorderColor: 'rgba(var(--vf-gray-500-rgb), 0.36)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlFocusBorderColor: 'var(--vf-primary-color)',
    controlFocusRing: 'var(--vf-focus-ring-shadow)',
    dangerTextColor: 'var(--vf-danger-color)',
    dangerBorderColor: 'rgba(var(--vf-red-600-rgb), 0.5)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};

