export default {
    gap: '0.5rem',
    textColor: 'var(--vf-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    boxSize: '1rem',
    boxBorderRadius: 'var(--vf-radii-sm)',
    boxBorderColor: 'var(--vf-border-color)',
    boxBackgroundColor: 'var(--vf-bg-color)',
    boxCheckedBackgroundColor: 'var(--vf-blue-600)',
    boxCheckedBorderColor: 'var(--vf-blue-600)',
    boxCheckColor: '#ffffff',
    boxCheckRadius: '2px',
    radioSize: '1rem',
    radioBorderColor: 'var(--vf-border-color)',
    radioBackgroundColor: 'var(--vf-bg-color)',
    radioCheckedBackgroundColor: 'var(--vf-blue-600)',
    radioCheckedBorderColor: 'var(--vf-blue-600)',
    radioDotSize: '0.45rem',
    radioDotColor: '#ffffff',
    switchWidth: '2.2rem',
    switchHeight: '1.2rem',
    switchThumbSize: '0.9rem',
    switchThumbOffset: '0.15rem',
    switchThumbTranslateOffset: '0.3rem',
    switchBackgroundColor: 'var(--vf-gray-400)',
    switchCheckedBackgroundColor: 'var(--vf-blue-600)',
    switchThumbColor: '#ffffff',
};
