export default {
    minWidth: '12rem',
    fontSize: 'var(--vf-typography-font-size)',
    controlGap: '0.75rem',
    chevronSize: '0.9em',
    padding: 'var(--vf-controls-padding-y) var(--vf-controls-padding-x)',
    borderRadius: 'var(--vf-radii-md)',
    borderColor: 'var(--vf-border-color)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    focusBorderColor: 'var(--vf-blue-600)',
    hoverBorderColor: 'var(--vf-blue-500)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    panelBackgroundColor: 'var(--vf-bg-color)',
    panelBorderColor: 'var(--vf-border-color)',
    panelPadding: '0.35rem',
    panelMaxHeight: '16rem',
    panelRadiusOffset: '2px',
    panelShadow: '0 10px 30px rgba(0, 0, 0, 0.12)',
    focusRingShadow: 'var(--vf-states-focus-ring-shadow)',
    optionPadding: '0.5rem 0.6rem',
    optionBorderRadius: 'var(--vf-radii-md)',
    optionHoverBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.08)',
    optionActiveBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    optionActiveTextColor: 'var(--vf-text-color)',
    small: {
        padding: '0.375rem 0.5rem',
        fontSize: '0.875rem',
    },
    large: {
        padding: '0.625rem 0.875rem',
        fontSize: '1.125rem',
    },
};
