export default {
    gap: '0.5rem',
    controlsGap: '0.4rem',
    controlSize: '1.85rem',
    controlRadius: 'var(--vf-radii-sm)',
    controlBorderColor: 'var(--vf-border-color)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    itemPadding: '0.35rem 0.65rem',
    itemBorderRadius: 'var(--vf-radii-sm)',
    itemBorderColor: 'var(--vf-border-color)',
    itemBackgroundColor: 'var(--vf-bg-color)',
    itemTextColor: 'var(--vf-text-color)',
    itemHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    itemActiveBackgroundColor: 'rgba(var(--vf-blue-600-rgb), 0.14)',
    itemActiveTextColor: 'var(--vf-text-color)',
    itemActiveBorderColor: 'rgba(var(--vf-blue-600-rgb), 0.45)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
