export default {
    gap: '1rem',
    itemGap: '0.75rem',
    lineThickness: '2px',
    lineLength: '1.5rem',
    lineColor: 'var(--vf-border-color)',
    indicatorSize: '2rem',
    indicatorBorderRadius: '999px',
    indicatorBorderWidth: '1px',
    indicatorFontSize: '0.875rem',
    indicatorBackgroundColor: 'var(--vf-bg-color)',
    indicatorTextColor: 'var(--vf-secondary-text-color)',
    indicatorBorderColor: 'var(--vf-border-color)',
    activeIndicatorBackgroundColor: 'var(--vf-blue)',
    activeIndicatorTextColor: 'var(--vf-white)',
    activeIndicatorBorderColor: 'var(--vf-blue)',
    completedIndicatorBackgroundColor: 'var(--vf-green)',
    completedIndicatorTextColor: 'var(--vf-white)',
    completedIndicatorBorderColor: 'var(--vf-green)',
    errorIndicatorBackgroundColor: 'var(--vf-red)',
    errorIndicatorTextColor: 'var(--vf-white)',
    errorIndicatorBorderColor: 'var(--vf-red)',
    labelFontSize: 'var(--vf-typography-font-size)',
    labelColor: 'var(--vf-text-color)',
    descriptionFontSize: '0.875rem',
    descriptionColor: 'var(--vf-secondary-text-color)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
    small: {
        indicatorSize: '1.5rem',
        indicatorFontSize: '0.75rem',
        labelFontSize: '0.875rem',
        descriptionFontSize: '0.75rem',
        lineLength: '1.25rem',
        itemGap: '0.5rem',
    },
    large: {
        indicatorSize: '2.5rem',
        indicatorFontSize: '1rem',
        labelFontSize: '1.125rem',
        descriptionFontSize: '1rem',
        lineLength: '1.75rem',
        itemGap: '1rem',
    },
};
