export default {
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radius-md)',
    backgroundColor: '#111827',
    textColor: '#e5e7eb',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.875rem',
    toolbarPadding: '0.5rem 0.75rem',
    actionsGap: '0.5rem',
    actionBorderColor: 'var(--vf-border-color)',
    actionRadius: 'var(--vf-radius-sm)',
    actionBackgroundColor: '#1f2937',
    actionTextColor: '#e5e7eb',
    actionPadding: '0.25rem 0.625rem',
    dividerColor: 'rgba(229, 231, 235, 0.2)',
    bodyPadding: '0.75rem',
    entryGap: '0.5rem',
    timeFontSize: '0.75rem',
    timeColor: '#9ca3af',
    promptColor: '#60a5fa',
    entryNeutralColor: '#e5e7eb',
    entryInfoColor: '#93c5fd',
    entrySuccessColor: '#86efac',
    entryWarnColor: '#fcd34d',
    entryErrorColor: '#fca5a5',
    emptyColor: '#9ca3af',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
