export default {
    gap: '1rem',
    itemGap: '0.75rem',
    markerSize: '1.75rem',
    markerBorderRadius: '999px',
    markerBorderWidth: '1px',
    markerBackgroundColor: 'var(--vf-bg-color)',
    markerBorderColor: 'var(--vf-border-color)',
    markerTextColor: 'var(--vf-text-color)',
    markerIconSize: '0.875rem',
    dotSize: '0.5rem',
    lineThickness: '2px',
    lineLength: '1.5rem',
    lineColor: 'var(--vf-border-color)',
    titleFontSize: 'var(--vf-typography-font-size)',
    titleColor: 'var(--vf-text-color)',
    descriptionFontSize: '0.875rem',
    descriptionColor: 'var(--vf-secondary-text-color)',
    dateFontSize: '0.75rem',
    dateColor: 'var(--vf-secondary-text-color)',
    info: {
        markerBackgroundColor: 'var(--vf-blue-100)',
        markerBorderColor: 'var(--vf-blue)',
        markerTextColor: 'var(--vf-blue-700)',
        lineColor: 'var(--vf-blue-200)',
    },
    success: {
        markerBackgroundColor: 'var(--vf-green-100)',
        markerBorderColor: 'var(--vf-green)',
        markerTextColor: 'var(--vf-green-700)',
        lineColor: 'var(--vf-green-200)',
    },
    warn: {
        markerBackgroundColor: 'var(--vf-yellow-100)',
        markerBorderColor: 'var(--vf-yellow)',
        markerTextColor: 'var(--vf-yellow-700)',
        lineColor: 'var(--vf-yellow-200)',
    },
    danger: {
        markerBackgroundColor: 'var(--vf-red-100)',
        markerBorderColor: 'var(--vf-red)',
        markerTextColor: 'var(--vf-red-700)',
        lineColor: 'var(--vf-red-200)',
    },
    small: {
        itemGap: '0.5rem',
        markerSize: '1.375rem',
        markerIconSize: '0.75rem',
        dotSize: '0.375rem',
        lineLength: '1.125rem',
        dateFontSize: '0.6875rem',
        titleFontSize: '0.875rem',
        descriptionFontSize: '0.75rem',
    },
    large: {
        itemGap: '1rem',
        markerSize: '2.125rem',
        markerIconSize: '1rem',
        dotSize: '0.625rem',
        lineLength: '1.875rem',
        dateFontSize: '0.8125rem',
        titleFontSize: '1.125rem',
        descriptionFontSize: '1rem',
    },
};
