export default {
    gap: '0.75rem',
    padding: '0.9rem',
    minHeight: '8rem',
    borderColor: 'var(--vf-border-color)',
    borderRadius: 'var(--vf-radii-lg)',
    backgroundColor: 'var(--vf-bg-color)',
    textColor: 'var(--vf-text-color)',
    controlsGap: '0.5rem',
    controlPadding: '0.35rem 0.65rem',
    controlRadius: 'var(--vf-radii-sm)',
    controlBorderColor: 'var(--vf-border-color)',
    controlBackgroundColor: 'var(--vf-bg-color)',
    controlTextColor: 'var(--vf-text-color)',
    controlHoverBackgroundColor: 'var(--vf-bg-soft-color)',
    transitionDuration: '180ms',
    transitionTiming: 'ease',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
