export default {
    gap: '1rem',
    borderColor: 'var(--vf-border-color)',
    headerPaddingBottom: '0.75rem',
    itemGap: '0.75rem',
    stepGap: '0.5rem',
    indicatorSize: '1.75rem',
    indicatorBorderRadius: '999px',
    indicatorFontSize: '0.8125rem',
    indicatorBorderColor: 'var(--vf-border-color)',
    indicatorBackgroundColor: 'var(--vf-bg-color)',
    indicatorTextColor: 'var(--vf-secondary-text-color)',
    activeIndicatorBorderColor: 'var(--vf-blue)',
    activeIndicatorBackgroundColor: 'var(--vf-blue)',
    activeIndicatorTextColor: 'var(--vf-white)',
    completedIndicatorBorderColor: 'var(--vf-green)',
    completedIndicatorBackgroundColor: 'var(--vf-green)',
    completedIndicatorTextColor: 'var(--vf-white)',
    errorIndicatorBorderColor: 'var(--vf-red)',
    errorIndicatorBackgroundColor: 'var(--vf-red)',
    errorIndicatorTextColor: 'var(--vf-white)',
    titleFontSize: '0.95rem',
    titleColor: 'var(--vf-text-color)',
    descriptionFontSize: '0.8125rem',
    descriptionColor: 'var(--vf-secondary-text-color)',
    actionsGap: '0.5rem',
    buttonMinWidth: '4.5rem',
    buttonPadding: '0.4rem 0.7rem',
    buttonBorderRadius: 'var(--vf-radii-md)',
    buttonBorderColor: 'var(--vf-blue-600)',
    buttonBackgroundColor: 'var(--vf-blue-600)',
    buttonTextColor: 'var(--vf-white)',
    buttonHoverBackgroundColor: 'var(--vf-blue-700)',
    secondaryButtonBorderColor: 'var(--vf-border-color)',
    secondaryButtonBackgroundColor: 'transparent',
    secondaryButtonTextColor: 'var(--vf-text-color)',
    secondaryButtonHoverBackgroundColor: 'rgba(var(--vf-gray-600-rgb), 0.12)',
    disabledOpacity: 'var(--vf-states-disabled-opacity)',
};
